### ISSUE TITLE
Compile MKL-DNN on Windows problems

### ISSUE THREAD

**Issue by adhere** [01org/mkl-dnn#101]
I want to compile MKL-DNN on windows for[ Intel Caffe](https://github.com/intel/caffe). I read those issues [Windows or OSX Support?](https://github.com/01org/mkl-dnn/issues/10)  , [so many error when compiling on windows with visual studio](https://github.com/01org/mkl-dnn/issues/24), [mkl-dnn windows port ](https://github.com/01org/mkl-dnn/pull/54). And I see the current MKL-DNN CMakeLists.txt contains a setting for Windows(if(WIN32)). 

I believe the current  MKL-DNN supporting Windows. Right?

My development environment is:
OS：Windows 7 Ultimate SP1 64 （CPU is Intel Xeon E3-1231 V3）
IDE: VS2013
Toolset: [parallel_studio_xe_2017_update4_setup](http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11549/parallel_studio_xe_2017_update4_setup.exe)

What I do:

1. git clone https://github.com/01org/mkl-dnn
2. add a line to CmakeLists.txt 
list(APPEND CMAKE_FIND_ROOT_PATH "D:/caffe_intel/mklml_win_2018.0.20170720")
3. open a cmd window, cd to the mkl-dnn source directory; mkdir build; cd build
4. cmake -G "Visual Studio 12 2013 Win64" -T"Intel C++ Compiler 17.0" ..
5. Use the VS open the generated project. But building the the project is failed. The error：

> error	3	error : identifier "constexpr" is undefined	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	73	1	mkldnn
error	4	error : expected a ";"	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	73	1	mkldnn
error	5	error : identifier "constexpr" is undefined	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	75	1	mkldnn
error	6	error : expected a ";"	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	75	1	mkldnn
error	7	error #77: this declaration has no storage class or type specifier	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	129	1	mkldnn
error	8	error : "constexpr" is not a function or static data member	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	129	1	mkldnn
Warn	9	warning #12: parsing restarts here after previous syntax error	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	134	1	mkldnn
error	10	error : expected a ";"	D:\caffe_intel\mkl-dnn-master\src\common\utils.hpp	134	1	mkldnn
error	11	error : identifier "constexpr" is undefined	D:\caffe_intel\mkl-dnn-master\src\common\nstl.hpp	47	1	mkldnn
error	12	error : expected a ";"	D:\caffe_intel\mkl-dnn-master\src\common\nstl.hpp	47	1	mkldnn
error	13	error #303: explicit type is missing ("int" assumed)	D:\caffe_intel\mkl-dnn-master\src\common\nstl.hpp	52	1	mkldnn
error	14	error : expected a ";"	D:\caffe_intel\mkl-dnn-master\src\common\nstl.hpp	52	1	mkldnn
error	15	error #303: explicit type is missing ("int" assumed)	D:\caffe_intel\mkl-dnn-master\src\common\nstl.hpp	57	1	mkldnn

Any suggestions to compile MKL-DNN on Windows or there is a pre-build binary one ? Thanks!

**Comment by vpirogov** [comment]
We don't have binary distribution for Intel MKL-DNN on any platforms. While current version of MKL-DNN can be built on Windows it has limited functionality and validated platforms. The errors you observe are due to limited C++11 support in VS 2013, namely it does not understand `constexpr` keyword. You should be able to compiler using VS 2015. Hope that helps!

**Comment by nhkrishna** [comment]
I'm also trying to use mkl-dnn in windows environment , while building in visual studio it giving some linking errors. I've included all the lib and include files that are need to build . but still problem persists. could you please look into this attachment and let us know if anything missing here ? 
![buildinwindowsproblem](https://user-images.githubusercontent.com/10693129/35392596-6d3af1a4-0208-11e8-8e93-abcc58553e80.PNG)
