### ISSUE TITLE
who can explain the association among MKL, MKLML, MKLDNN

### ISSUE THREAD

**Issue by buaasun** [01org/mkl-dnn#102]
I'm confused with the three: MKL MKLML MKLDNN?
Is there a runtime dependency in the three?

**Comment by rsdubtso** [comment]
* MKL is a full library, containing all the functionality. It is free under community support licensing (https://software.intel.com/en-us/articles/free-mkl).

* MKLML is a subset of MKL and it's built by the MKL release team using standard MKL custom dynamic library builder. It contains smaller number of functions to reduce the size of the download and reduce the number of dynamic libraries user needs.

* MKLDNN is a separate open-source library actually developed by one of the MKL teams and that can be built completely standalone. But it does support linking with MKLML or full MKL for additional performance.

Hope this helps. Feel free to ask any further questions.

**Comment by buaasun** [comment]
many thanks

**Comment by anamasi26** [comment]
ناتج محب ناتج القحيب ملايين

**Comment by anamasi26** [comment]
ملاحج ملااحج وكمان دستولي ابيض

**Comment by anamasi26** [comment]
كلام العيم مكتبه همم وكلام العين همدسه مكتبه مكتبيه هندسه مكاتب

**Comment by pengzhao-intel** [comment]
@rsdubtso The great explanation! Is it possible to add it into README page?

**Comment by bobuntu** [comment]
@rsdubtso, are there any other changes since MKLDNN is rebranding into DNNL?

**Comment by vpirogov** [comment]
Hi @bobuntu,

The new name of the project is **oneDNN**. In addition to this starting from v1.0 the library has fully performant implementation of GEMM functionality and does not support linking to Intel MKL (or MKLML). We also stopped distributing MKLML package.
