### ISSUE TITLE
Is ANY batch size supported for inference?

### ISSUE THREAD

**Issue by heagoo** [01org/mkl-dnn#103]
I see the batch size is fixed in the example simple_net.cpp. Does it support any batch size? that is to say, initialize with any batch size, but feed with the real batch size on the fly. Thanks!

    **const int batch = 8;**

    std::vector<float> net_src(batch * 3 * 227 * 227);
    std::vector<float> net_dst(batch * 96 * 27 * 27);

    /* AlexNet: conv
     * {batch, 3, 227, 227} (x) {96, 3, 11, 11} -> {batch, 96, 55, 55}
     * strides: {4, 4}
     */
    memory::dims conv_src_tz = {batch, 3, 227, 227};
    memory::dims conv_weights_tz = {96, 3, 11, 11};
    memory::dims conv_bias_tz = {96};
    memory::dims conv_dst_tz = {batch, 96, 55, 55};
    memory::dims conv_strides = {4, 4};
    auto conv_padding = {0, 0};

**Comment by rsdubtso** [comment]
We do not support changing batch size on the fly. You need to create primitives and use them with the same batch size. I'm not sure there's good error reporting, though.

**Comment by heagoo** [comment]
Got, thanks!
