### ISSUE TITLE
why my program can't run parallelly even I set OMP_NUM_THREADS?

### ISSUE THREAD

**Issue by buaasun** [01org/mkl-dnn#104]
I can run test `test_convolution_forward_f32` and the CPU utilization can reach 3000%, but my own code seems only utilize 100% CPU.
Here is my test code `examples/test_softmax.cpp`
```c++  


#include <iostream>
#include <numeric>
#include "mkldnn.hpp"

using namespace mkldnn;

void test_softmax(int N) {
  auto cpu_engine = engine(engine::cpu, 0);
  static const memory::format format_nchw = memory::format::nchw;
  static const memory::data_type data_type = memory::data_type::f32;

  std::vector<float> in(N * N, 1); //{0.8401877, 0.7830992,0.3943829, 0.79844};
  std::vector<float> out(N * N, 1);//={0.9116474, 0.3352228,0.1975514, 0.7682296};

  memory::dims src_tz = {N, N, 1, 1};
  auto src_memory = memory({{{src_tz}, data_type, format_nchw}, cpu_engine}, in.data());
  auto dst_memory = memory({{{src_tz}, data_type, format_nchw}, cpu_engine}, out.data());
  auto src_md = memory::desc({src_tz}, data_type, format_nchw);
  auto softmax_desc = softmax_forward::desc(prop_kind::forward_scoring, src_md, 0);
  auto softmax_pd = softmax_forward::primitive_desc(softmax_desc, cpu_engine);
  auto softmax = softmax_forward(softmax_pd, src_memory, dst_memory);
  stream(stream::kind::eager).submit({softmax}).wait();
}

int main(int argc, char **argv) {
  try {
    int N = atoi(argv[1]);
    test_softmax(N);
  } catch (error &e) {
    std::cerr << "status: " << e.status << std::endl;
    std::cerr << "message: " << e.message << std::endl;
  }
  return 0;
}

```
Here is CMake code which I add to `examples/CMakeLists.txt`
```c++
add_executable(test_softmax test_softmax.cpp)
set_property(TARGET test_softmax PROPERTY CXX_STANDARD 11)
target_link_libraries(test_softmax ${LIB_NAME})
add_test(test_softmax test_softmax)
```
I built the code, then ran
```
OMP_NUM_THREADS=16 examples/test_softmax 10000
```
I found it is much slower than similar program writen by Eigen library, and the CPU utilization of the process can only reach 100%, seems it can only use one CPU core.
Is there any problem with my code, or  I missed any other configuration?

**Comment by vpirogov** [comment]
Hi @buaasun,

Your code looks ok. The library includes only reference implementation of softmax function that you are using. This implementation is sequential and it cannot take advantage of multiple threads.

**Comment by emfomenk** [comment]
Hi @buaasun,

As @vpirogov mentioned we indeed don't have an optimized (parallel) version of softmax.
I just want to confirm you wanted to perform softmax along first dimension:
```
auto softmax_desc = softmax_forward::desc(prop_kind::forward_scoring, src_md, 0);
```

Typically (e.g. in the last layer of many topologies in Caffe) the softmax_axis is **1** (i.e. minibatch is independent variable and channels are classes):
```
auto softmax_desc = softmax_forward::desc(prop_kind::forward_scoring, src_md, 1);
```

Once changed `./test_softmax 10000` took 0.3 sec instead of 22 sec on 16 threads.

**Comment by buaasun** [comment]
Hi @emfomenk ,
Yes, after change axis to 1, the program becomes much faster.
BTW, What does the parameter axis mean? I think minibatch is dimension 0 and class is dimension 1 and I want to compute softmax by minibatch-wise.  Why should the axis parameter be 1 instead of 0? Besides, is the tensor data stores in `ColMajor` format or `RowMajor` format?

**Comment by vpirogov** [comment]
API works with logical dimensions notations which is always NCHW for 4D tensors as in your example. In this notation 1 stands for channels. This has nothing to do with physical data layout, the function will work with any provided layout (performance may vary, though). Softmax will take values in subtensor defined by axis and put them into (0,1) range with a sum of values equal to 1. Dimensions with index less than axis are considered independent variables, dimensions equal or greater to axis index form a subtensor. In case of axis = 1 minibatch (N) becomes independent variable and CHW define subtensor. In case of axis = 0 there are no independent variables and whole tensor gets normalized. The difference in performance you see is the result of the second case not being optimized.

**Comment by vpirogov** [comment]
In our data format notations dimensions listed last are changing the fastest. This corresponds to row major array notation.
