### ISSUE TITLE
what's the difference between mkldnn.h and mkl_dnn.h

### ISSUE THREAD

**Issue by buaasun** [01org/mkl-dnn#108]
I found `mkldnn.h` in `include` directory and `mkl_dnn.h` in `external/mklml_lnx_2018.0.20170425/include/` directory and the two file is quite different .
I also noticed that caffe actually use `mkl_dnn.h` in  (https://github.com/intel/caffe/blob/master/include/mkl_dnn_cppwrapper.h)
Now I'm confused which one should I use.

**Comment by vpirogov** [comment]
`mkldnn.h` and `mkldnn.hpp` are headers defining Intel MKL-DNN C and C++ APIs. These are the headers you want to use with Intel MKL-DNN.

`external/mklml_lnx_2018.0.20170425` contains a subset of [Intel MKL](https://software.intel.com/en-us/mkl) functionality. The only function that Intel MKL-DNN is using from this binary is SGEMM, however the subset itself supports other applications and include more functions. In particular, Intel MKL has it's own DNN functionality which uses API different for Intel MKL-DNN. This is what `mkl_dnn.h` is about.
