### ISSUE TITLE
weight or src at simple_net?

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#11]
I think I found an error at line:89 of examples/simple_net.cpp.
Maybe it should be conv_prim_desc.weights_primitive_desc(), not conv_prim_desc.src_primitive_desc().

What's weird is that both can pass the test, why?

**Comment by emfomenk** [comment]
Hi @tensor-tang,

Thanks for pointing to this issue. You are right, this is a typo indeed.
The test passes for two reasons:
- reorder doesn't check consistency of input and output memory
- there is no actual check of the obtained result, so even the result is garbage the example is care...

Will fix this soon. Thanks!
