### ISSUE TITLE
Confusing design about reorder and memory

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#110]
Example first:
I want to use `reorder `to transpose two `memory`
src: format: `io` dims: `{2, 3}` 
dst: format: `oi` dims: `{3, 2}`.

However when I use `reorder(src, dst)`, the dims need to be exactly the same. (This is also hard to understand, why not the dim follow the format chaning?)
Then got a question, choose `{2,3}` or `{3,2}` ?
This is a bit confusing for me. What's the rule users should follow?

As far as I can see now, this dims always followed `oi` format no matter it's src or dst memory.
Why like this? Am I wrong? 

By the way, I thought if I want to reorder `nChw8c` to `nhwc` the dims should be` {n, c/8, h, w, 8}` to `{n, h, w, c}` corresponding, then it's simply to me to understand. Otherwise I should use the dim of {n, c, h, w} of format `nchw` to deal with this case, which should be confusing for user.

Another issue, 
> This is also hard to understand, why not the dim follow the format chaning?

After reorder, the data buffer actually transposed indeed.
But it did not change the format, that's weird as well.
For example, user reorder `src({2, 3}, oi)` to `io` format, the result he got should be `dst({2,3}, io)` (**the {2,3} not changing**). Then he want to use the dst memory following the dims to read the data, then should be a error, since the correct dim should be {3,2} now!

**Comment by rsdubtso** [comment]
Hi @tensor-tang, we have decided that order of values in dims is always fixed and represents the 'logical' dimensions of the tensor. The memory format is 'physical' and is a separate matter. This actually makes things easier because the format is not always known beforehand and yet you still need to be able to describe tensor dimensions. Hope this helps...

**Comment by tensor-tang** [comment]
Thanks @rsdubtso, Yeah, I can understand your point.

But,
> that order of values in dims is always fixed and represents the 'logical' dimensions of the tensor.
But like the case io to oi, how users can understand which dim to choose, {2, 3} or {3, 2}, to init the two memory?
Most likely user would init memory follow the format in dims, then they would got error when reorder here.

And another case, if we train on BDW, then want to inference on other platform like KNL or FPGA.
Then we should at least save the weight format and dims on BWD like `OIhw8i8o`, but when reorder the weight to another platform the dims saved would not be correct then.

**Comment by rsdubtso** [comment]
> like the case io to oi, how users can understand which dim to choose, {2, 3} or {3, 2}, to init the two memory?
Most likely user would init memory follow the format in dims, then they would got error when reorder here.

Well, of course when you are initializing data explicitly you have to know the layout, there's no getting around that. But that init happens outside of MKL-DNN, right? Typically, the data is read in `nchw` or `nhwc` formats and then converted using MKL-DNN primitives. I am probably missing something here...

> And another case, if we train on BDW, then want to inference on other platform like KNL or FPGA.
Then we should at least save the weight format and dims on BWD like OIhw8i8o, but when reorder the weight to another platform the dims saved would not be correct then.

This is a very good point. I do not think we have a solution for this rather than converting to a known 'stable' format like `nchw` every time you write a data to be used later. I think this is what IntelCaffe does.

**Comment by tensor-tang** [comment]
>  But that init happens outside of MKL-DNN, right?

In common use I thought the `memory` can be used outside MKL-DNN.
User can directly init a memory like this:
```
auto src = memory(memory::primitive_desc({{2, 3}, f32, io}, engine), src_data);
auto dst = memory(memory::primitive_desc({{3, 2}, f32, oi}, engine), dst_data);
```
This makes perfect sense to me. The src_data and dst_data buffer has been created outside. 

And the src is input and filled with some useful data, then he want to convert src to dst of which memory has also been created. 

And use `reorder(src, dst)` to implement this convert. Then he may get an error, since the dims size do not equal.

What he need to do is to create another `memory` like this:

`auto src_tmp = memory(memory::primitive_desc({{**3, 2**}, f32, io}, engine), src_data);`

Then `reorder(src_tmp, dst)`, which is weird and confusing for user, right?



>  I think this is what IntelCaffe does.

Yeah, Thanks. I confirmed with that, IntelCaffe only save `cpu_data`.

**Comment by rsdubtso** [comment]
> What he need to do is to create another memory like this:
> ```auto src_tmp = memory(memory::primitive_desc({{**3, 2**}, f32, io}, engine), src_data);```
> Then reorder(src_tmp, dst), which is weird and confusing for user, right?

Okay, now I get your point. And I understand that this is confusing. However, I believe this is a reasonable tradeoff compared to what might have happened if we tried matching the order in tensor dims to format. For example: MKL-DNN supports blocked formats and it would have to map those to some canonical ones before validating the dims. But the choice of canonical formats is not trivial. For example, I see two options for `nChw16c` -- `nchw` and `nhwc`, and either would be causing some confusion...

**Comment by tensor-tang** [comment]
Yeah, for the blocked formats, like I said:

>  I thought if I want to reorder nChw8c to nhwc the dims should be{n, c/8, h, w, 8} to {n, h, w, c} corresponding, then it's simply to me to understand

Because I thought for those who know when to use `nChw8c` should have this knowledge what does it mean, and should also be acquired to know.

Anyway, this is just my own view and concern, thanks @rsdubtso

**Comment by rsdubtso** [comment]
Okay. Closing then. Thanks for the discussion.
