### ISSUE TITLE
Xeon Phi (Knight Corner) support

### ISSUE THREAD

**Issue by kclim2** [01org/mkl-dnn#113]
Any reason Knight Corner series is not in the list of supported device for MKL-DNN?

**Comment by vpirogov** [comment]
The first generation of Intel Xeon Phi coprocessor (code named Knights Corner) is in the end of life stage. While Intel MKL-DNN will likely run without problems we did not optimize or validate the library for this hardware. We fully support Intel Xeon Phi processor (code named Knights Landing) and future Intel Xeon Phi processor (code named Knights Mill)
