### ISSUE TITLE
How to support dynamic height and width?

### ISSUE THREAD

**Issue by heagoo** [01org/mkl-dnn#114]
For the case that image height and width varies all the time, any solutions to use MKL-DNN (for inference)?
Thanks!

**Comment by heagoo** [comment]
Is it possible to set a maximum height and width

**Comment by rsdubtso** [comment]
Hi @heagoo, 

MKL-DNN primitives often are optimized for particular tensor dimensions at creation time, so it is not possible to specify max dimensions. If there is a limited set of dimensions, you could pre-create a primitive for each of those. A typical solution is to pre-scale images to the same dimensions.

**Comment by heagoo** [comment]
Thanks!
