### ISSUE TITLE
[Question]Difference between Stream and lazy of CPU engine and Eager

### ISSUE THREAD

**Issue by 0shimax** [01org/mkl-dnn#115]
As the title says.

**Comment by rsdubtso** [comment]
*Summary*: please don't use lazy streams.

*Longer answer*: Initially there was a planned feature to do some optimization on primitives submitted to a lazy stream. The stream would 'buffer' them until `wait()` is called, then do optimizations and then you would be able to re-run the stream with all the optimizations applied. Currently, non of  the optimizations happen and the stream just does the buffering. We are considering deprecating this mode.

**Comment by 0shimax** [comment]
@rsdubtso 
Thank you for your quick reply. 
I got it. I never use lazy.
