### ISSUE TITLE
[Question] Efficiency of Stream

### ISSUE THREAD

**Issue by 0shimax** [01org/mkl-dnn#117]
Is it more efficient to run with Stream  with all primitives and wait()?  How much does it differ from wait whenever one primitive is executed?

**Comment by emfomenk** [comment]
Hi @0shimax,

There should be no difference between approaches.
If you put many primitives into the single stream, you will avoid negligible overhead of putting each single primitive prior to the run. But basically it's nothing in terms of performance.
So please proceed with whatever is more convenient for you.

Please see also this [issue](https://github.com/01org/mkl-dnn/issues/115).

**Comment by 0shimax** [comment]
@emfomenk 
Thank you for the clear answer.
I thought this question is related to #115, and your answer was so.
As in your advice, I use convenient one for me.
