### ISSUE TITLE
we find XMM8-16 registers will be modified by MKL-DNN after mkldnn_excute()

### ISSUE THREAD

**Issue by a3213105** [01org/mkl-dnn#119]
only on win64 system. And the Intel manual says XMM 8-16 should be protected by callee

**Comment by rsdubtso** [comment]
I think we have a fix for in c23f8c495a74da5c22c18f15f35bd88dc131c4c3. Can you please provide a testcase?

**Comment by a3213105** [comment]
thanks @rsdubtso, i see the commit date is  13 Jul, i use the mkl lib from the parallel studio. maybe this commit is not merge into the lib which i used. i will try the latest release v0.10 first :).
if i have any question， i will ask you， thanks a lot

**Comment by rsdubtso** [comment]
The mkl that comes with the studio is a separate product and is not API compatible. And it may have this bug depending on which version you use.

**Comment by vpirogov** [comment]
The issue does not affect Intel MKL-DNN, so I will close it on Github. In Intel MKL 2018 at least LRN implementation does not restore xmm8-16 on Windows, I created an internal defect to track this.
