### ISSUE TITLE
Atom roadmap

### ISSUE THREAD

**Issue by bhack** [01org/mkl-dnn#12]
We are evaluating mkl-dnn as one of the accellaeration engines avaialble in https://github.com/tiny-dnn/tiny-dnn.
It will be target also for Intel embedded platforms like Atom series and others?

**Comment by beru** [comment]
@bhack Shouldn't this issue be created on tiny-dnn issues considering its title..?

**Comment by bhack** [comment]
Yes but I don't know if as policy project members can reply to other repositories. And it is strictly releated to mkl-roadmap. I can try to redit the title but probably this issue will has a short life.

**Comment by rsdubtso** [comment]
Atom optimizations are not on the roadmap now.

**Comment by bhack** [comment]
@rsdubtso Thank you. But are you pointing to another library for Intel Atom or other Intel embedded platforms or actually there is any solution for this kind of devices?

**Comment by rsdubtso** [comment]
@bhack I do not know. Maybe @vpirogov has a better answer to this question.

**Comment by vpirogov** [comment]
We have just added JIT optimizations for Intel(R) SSE4, check it out.

**Comment by vpirogov** [comment]
With the latest changes the library is fully functional on Intel Atom processors and includes convolution optimizations for Intel SSE 4.2. There are a few things in the pipeline, but the key optimizations are there.
