### ISSUE TITLE
test_convolution_forward_f32 crashed with a specific case

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#122]
hi,
I just run into a case below:

`PARAMS(nchw, oihw, FMT_BIAS, nchw, 10, 1, 32, 81, 980, 32, 41, 980, 21, 11, 10, 5, 2, 1, 0, 0)`

but result in
 > Segmentation fault (core dumped)

OS: CentOS 7.2
HW: Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
DIMMS: 64G

Is that out of memory?  But found %MEM grows up to about 77.9%.
Any comment?
Thanks very much.

**Comment by vpirogov** [comment]
This convolution does not have JIT optimized path and runs using GEMM implementation. GEMM-based convolution starts with operation called im2col, that copies data to temporary buffer of large size while duplicating some of the elements. As this case has rather large kernel resulting buffer size exceeds capacity of int32 data type leading to overflow. Patch will be promoted shortly.

This won't solve the memory consumption issue though, as im2col will still be used. Dealing with it requires specialized JIT code for large kernels.

**Comment by vpirogov** [comment]
Resolved in 8eebaffdaf0ab19a64ad2e0917c6ec83b5e9a721
