### ISSUE TITLE
Does mkl-dnn provide some performance boost for fully-connected NN's? 

### ISSUE THREAD

**Issue by snarb** [01org/mkl-dnn#124]
If someone needs to get max speed for a forward pass for a deep and wide fully-connected Relu NN's, will mkl-dnn help with this? As I understand major performance tuning work in mkl-dnn is done for convolutions and around it. I have tested TensorFlow built with mkl-dnn support  [TensorFlow* Optimizations on Modern Intel® Architecture](https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture) for FC network and it is much slower(2X for a forward pass) then TensorFlow SSE enabled build for Xenon.

**Comment by vpirogov** [comment]
InnerProduct should be able to do the trick in particular if you build Intel MKL-DNN with binary dependency, as performance mostly comes from optimized matrix-matrix multiplication.
