### ISSUE TITLE
Reuse descriptors without heap allocation

### ISSUE THREAD

**Issue by piiswrong** [01org/mkl-dnn#126]
Suppose I want to re-initialize the descriptors on every iteration because input shape changes, how can I avoid allocating memory for primitive descriptors and primitives? Can I cache the primitives in a thread_local store and re-initialize them every time? Or can I run forward with descriptors only and avoid creating primitive descriptors and primitives?

**Comment by vpirogov** [comment]
Hi @piiswrong,

You cannot avoid allocating memory for primitive descriptors, these require memory buffer, However once primitive descriptor is created you can cache and reuse it if there's a high chance that the shape will repeat. You'll just need to put new data in the memory associated with the primitive.

**Comment by piiswrong** [comment]
Do primitives structure for different shapes have different size?
It should be possible to allocate one primitive and reset it to different shape.

Like in cudnn you can do

cudnnCreateConvDesc()
cudnnSetConvDesc(shapes1)
...
codnnSetConvDesc(shapes2)

The benefit of this is you can avoid allocating and deallocating heap, which is the most expensive part.

**Comment by vpirogov** [comment]
There's no guarantees about structures size and you will need to create new descriptor whenever the shape changes. Do you observe performance issues with descriptor creation time?
