### ISSUE TITLE
WIN32 incorrect units for ms_now

### ISSUE THREAD

**Issue by kruus** [01org/mkl-dnn#128]
`ms_now()` should return **milli**seconds for WIN32 code

Fix by changing `std::micro` to `std::milli` in `tests/benchdnn/common.cpp`.

- this agrees with linux usage of `ms_now()`
- and with `tests/benchdnn/conv/perf_report.cpp` 'F' and 'p' output conversion lines.

**Comment by vpirogov** [comment]
Fixed in a0c315af6b39879fe8069ae887deaab511aee5df
