### ISSUE TITLE
benchdnn : backward RELU convolution error (please document or fix)

### ISSUE THREAD

**Issue by kruus** [01org/mkl-dnn#129]
Backward conv+RELU benchmarks (BWD_W, BWD_D, BWD_WB) fail in benchdnn:
```
run: --dir=BWD_W --merge=relu mb1ic3ih227oc96oh55kh11sh4nalexnet:conv1
error [int conv::init_pd(const conv::prb_t*, mkldnn_convolution_desc_t&, mkldnn_primitive_desc*&, res_t*):401]: 'mkldnn_convolution_relu_desc_init(&crd, &cd, 0)' -> mkldnn_invalid_arguments(3)
@@@ error [int conv::doit(const conv::prb_t*, res_t*):459]: 'init_pd(p, cd, cpd, r)' -> 1
0:UNTESTED (errors:0 total:0) __REPRO: --dir=BWD_W --merge=relu mb1ic3ih227oc96oh55kh11sh4nalexnet:conv1
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:1
```
Please fix or document in `benchdnn/TODO.md`
I won't look into fixing this backward+RELU issue.

I'm adding iterate-over-impls to benchdnn.
My main goal is to muck with new impls, at benchdnn level and then at mkldnn level.
Other benchdnn issues can wait until my code stabilizes and I prepare a PR for comments, but this may be a while.  If anyone wants benchdnn iterating over impls, I can try to get around to the PR it a little bit sooner.

**Comment by emfomenk** [comment]
Hi @kruus,

MKL-DNN doesn't support merged conv+relu for backward pass.
That means neither `--dir=BWD_W --merged=relu` nor `--dir=BWD_D --merged=relu` would work.
Basically benchdnn reports that `mkldnn_convolution_relu_desc_init()` returns `mkldnn_invalid_arguments`.

Benchdnn as a benchmark doesn't know what is implemented of the library side and what is not. So there is nothing to fix there (except adding the implementation in MKL-DNN of course). Maybe more meaningful warning regarding chosen configuration...

Or maybe I missed something.

**Comment by kruus** [comment]
You didn't miss anything. Thanks for clarification that this "works as intended". I'll add a note to docs.

**Comment by emfomenk** [comment]
I saw you added some documentation regarding c vs c++ and data types. Looks cool... 👍 
We'd better have something like that as well to simplify developers' life...

**Comment by kruus** [comment]
old notes-to-self upon a first look at the code... needs cleanup and updates, now that I look at it again. Adding doc update PR to my [long] todo list.

**Comment by kruus** [comment]
Oh, while I've got a thread, I finally think I found the source of a segfault issue that I noticed
months ago, and that came back to haunt me this week. The segfault happens (sometimes)
when you call `mkldnn_primitive_desc_iterator_destroy` (file `primitive_iterator.cpp`).

One way to fix it could involve setting `pd_` back to nullptr within `operator++` :
```
    primitive_desc_iterator_t &operator++() {
        if (pd_){
            delete pd_;
            pd_ = nullptr;
        }
```
helping the destructor not to **double-delete** `pd_`:
```
    ~mkldnn_primitive_desc_iterator() { if (pd_) delete pd_; }
```
(Thanks for clues, valgrind!)

**Comment by kruus** [comment]
After above bugfix, `benchdnn` iterate-over-impls code shaping up nicely:  with new bench_mode `ALL` (so `--skip-impls` becomes usable), just need to massage the stats/output code a bit more. Nice to use `benchdnn --mode=ACP -skip-impls=ref` and see the huge performance difference between avx2 and sse2 (and that all tested impls were correct) :smile:

**Comment by kruus** [comment]
Critical bug squashed in [PR 135](https://github.com/01org/mkl-dnn/pull/135)
