### ISSUE TITLE
AVX2 question

### ISSUE THREAD

**Issue by johnlilburne** [01org/mkl-dnn#13]
So do you need AVX2 instructions to run MKL-DNN? I've ported MKL-DNN to windows and it died at:

```
0000002D5FD130E7	vfmadd231ps		ymm0,ymm12,ymm15 
```

Saying illegal instruction, so I checked cpuid flags and YMM is enabled in XCR0, but it seems the AVX2 flag is not set. So that means the fused multiply add won't work, is that correct?

**Comment by johnlilburne** [comment]
Yeah, I answered my own question, judging from the name of some of the files, i.e. jit_avx2_* I guess AVX2 is required. And there is an FMA flag in cpuid results and its off on my cpu, which is strange, I have a fairly recent Core i7 so I don't know why AVX2 wouldn't be in there unless Intel makes some cheaper version missing advanced instructions for big box stores. Such a pain now that all that work porting to windows was for nothing.

**Comment by rsdubtso** [comment]
I'm sorry you are having troubles with running MKL-DNN after porting it to Windows. What is the brand string of you CPU? Knowing that, it is possible to check if your CPU is supposed to support AVX2 on ark.intel.com. I've looked at that site and I see that all i7 CPUs starting from the 4th gen support AVX2.

**Comment by johnlilburne** [comment]
So I have an i7-3630QM chip, I'm guessing that it more or less follows the convention that the first number after the dash is the generation. So I think I have a 3rd generation chipset would be my assumption, which would explain the lack of AVX2. Probably whoever manufactured the computer had some old CPU inventory or bought some overstock and decided to unload it. Here is what I did to verify what features were available, modified slightly from some code an Intel employee provided:
```
void print_intel_features() {
	int *abcd = (int*)calloc(4, sizeof(int));
	int FMA = (1 << 12),
		MOVBE = (1 << 22),
		OSXSAVE = (1 << 27),
		AVX2 = (1 << 5),
		BMI1 = (1 << 3),
		BMI2 = (1 << 8),
		LZCNT = (1 << 5);

	std::ostringstream ss;
	__cpuidex(abcd, 1, 0);
	ss << "FMA       = " << ((abcd[2] & FMA) == FMA ? "yes" : "no") << std::endl;
	ss << "MOVBE     = " << ((abcd[2] & MOVBE) == MOVBE ? "yes" : "no") << std::endl;
	ss << "OSXSAVE   = " << ((abcd[2] & OSXSAVE) == OSXSAVE ? "yes" : "no") << std::endl;

	__cpuidex(abcd, 7, 0);
	ss << "BMI1      = " << ((abcd[1] & BMI1) == BMI1 ? "yes" : "no") << std::endl;
	ss << "BMI2      = " << ((abcd[1] & BMI2) == BMI2 ? "yes" : "no") << std::endl;
	ss << "AVX2      = " << ((abcd[1] & AVX2) == AVX2 ? "yes" : "no") << std::endl;

	__cpuidex(abcd, 0x80000001, 0);
	ss << "LZCNT     = " << ((abcd[2] & LZCNT) == LZCNT ? "yes" : "no") << std::endl;
	free(abcd);

	uint32_t xcr0 = _xgetbv(0);
	ss << "YMM       = " << ((xcr0 & 6) == 6 ? "yes" : "no") << std::endl;
	write("G:/algo/intel.txt", ss.str(), true);
	std::cout << ss.str() << std::endl;

}
```
And it outputs:
```
FMA			= no
MOVBE		= no
OSXSAVE		= yes
BMI1		= no
BMI2		= no
AVX2		= no
LZCNT		= no
YMM		= yes
```

I think maybe it has AVX, otherwise why are the YMM registers there, but not AVX2. So I'm guessing all this points to the fact that I'll probably have to buy a new CPU to keep working on it, and make sure to save the receipt this time so I can return it if I find out later they gipped me with some old stuff.

**Comment by rsdubtso** [comment]
Right. i7-3630QM is an IvyBridge CPU (http://ark.intel.com/products/71459/Intel-Core-i7-3630QM-Processor-6M-Cache-up-to-3_40-GHz) which has AVX but not AVX2.
