### ISSUE TITLE
Does mkl-dnn currently support densenet?

### ISSUE THREAD

**Issue by HAIDJ** [01org/mkl-dnn#133]
Hello,

I wonder if mkl-dnn supoorts [densenet models](https://github.com/Tongcheng/DN_CaffeScript). (please check this models)
Is there any method to run densenet on MKLDNN?

I look forward to your reply.
Thank you.

**Comment by vpirogov** [comment]
This question is more about the framework capabilities than to Intel MKL-DNN functionality. Densenets use `DenseBlock` layer for memory efficient implementation which probably can be implemented using existing functions.

**Comment by HAIDJ** [comment]
I succeeded in executing DenseNet with MKL-DNN. 

Thank you for your reply.
