### ISSUE TITLE
test_sum failed with random input data

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#134]
Since mkldnn::sum tested some [cases ](https://github.com/01org/mkl-dnn/blob/master/tests/gtests/test_sum.cpp#L149) like from format `nChw8c` and `nChw8c` to `nchw`, I thought it should be supported now.

But when I use real data by uncommenting the [fill_data](https://github.com/01org/mkl-dnn/blob/master/tests/gtests/test_sum.cpp#L102), the gtest failed.

The reason gtest passed before is that all data used same value `for (ptrdiff_t j = 0; j < sz; ++j) s[j] = static_cast<data_t>(i + 1);`.

Seems `mkldnn::sum` do not support the cases with different src and dst format yet, right?
So the cases are fake test or just have not finished?

**Comment by emfomenk** [comment]
Hi @tensor-tang,

It's a shame about the test... :(
Of course it is just a typo, the data should be different for different places in a memory.

mkldnn::sum ought to work with different input layouts.
Basically that is the main purpose of the primitive -- avoiding unnecessary conversions.

Thanks for catching that. Will take a look!

**Comment by rsdubtso** [comment]
Fixed in 15f093e1ae495e0cfd7ec87180884865231b1a07.
