### ISSUE TITLE
_jit_sse42_convolution_fwd_t crashes

### ISSUE THREAD

**Issue by aBleauGenetec** [01org/mkl-dnn#138]
Tested on a CPU supporting SSE4.2, but not AVX, under Windows 10,  with benchdnn:

benchdnn --conv --mode=P --dir=FWD_D -v9 --perf-template=perf,%d,avg=%0tmsec g1mb1ic3ih227iw227oc96oh55ow55kh11kw11sh4sw4ph0pw0dh0dw0n"alexnet:conv1"

Output: 
run: --dir=FWD_D mb1ic3ih227oc96oh55kh11sh4nalexnet:conv1
mkldnn implementation: const char *__cdecl mkldnn::impl::cpu::_jit_sse42_convolution_fwd_t<0>::pd_t::name(void) const

Then a window pop-up: benchdnn.exe has stopped working.

Changing the input parameters slightly, so that another implementation is chosen works. Example, changing ic3 to ic1 above:

benchdnn --conv --mode=P --dir=FWD_D -v9 --perf-template=perf,%d,avg=%0tmsec g1mb1ic1ih227iw227oc96oh55ow55kh11kw11sh4sw4ph0pw0dh0dw0n"alexnet:conv1"

Output: 

run: --dir=FWD_D mb1ic1ih227oc96oh55kh11sh4nalexnet:conv1
mkldnn implementation: const char *__cdecl mkldnn::impl::cpu::_gemm_convolution_fwd_t<0,0,0>::pd_t::name(void) const
perf,--dir=FWD_D mb1ic1ih227oc96oh55kh11sh4nalexnet:conv1,avg=16.457msec
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0

I also tested the problematic case on a Xeon E5-1620v3 supporting AVX2:
run: --dir=FWD_D mb1ic3ih227oc96oh55kh11sh4nalexnet:conv1
mkldnn implementation: const char *__cdecl mkldnn::impl::cpu::_jit_avx2_convolution_fwd_t<0>::pd_t::name(void) const
perf,--dir=FWD_D mb1ic3ih227oc96oh55kh11sh4nalexnet:conv1,avg=2.65636msec
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0

Then I edited cpuengine.cpp to comment the line enabling the AVX2 implementation:
//INSTANCE(jit_avx2_convolution_fwd_t),
 and rerun. This time, _jit_sse42_convolution_fwd_t was selected and it crashed in the same manner as on the smaller CPU. I was able to attach a debugger and saw that it was due to an access violation.

- André Bleau, Genetec

**Comment by aBleauGenetec** [comment]
Thanks @rsdubtso! I tried your changes and it solves the issue.

**Comment by aBleauGenetec** [comment]
@rsdubtso,

I think you forgot jit_uni_batch_normalization, which also uses rcx.

**Comment by emfomenk** [comment]
Hi @aBleauGenetec,

Could you please point to exact line where you see batch-norm uses %rcx?
To be more precise, batch-norm uses %rcx via `reg_param=abi_param1` (which equals %rcx on Windows), but we should handle that correctly.

Do you still observe the problem?

**Comment by aBleauGenetec** [comment]
Hi @emfomenk,

In jit_uni_batch_normalization.cpp, lin 103 reads:
    Reg64 dst_simd_iter = rcx;
As I never used it, I never had a problem with it. I discovered it by searching the code for
= rcx

- André

**Comment by emfomenk** [comment]
Hi André,

Now I got it :) I haven't seen that line in repo, because it is already fixed by another [commit](https://github.com/rsdubtso/mkl-dnn/commit/f25939a284c459965ae6d6efa790e0a1f46f1f34).
@rsdubtso 's [repo](https://github.com/rsdubtso/mkl-dnn) is slightly ahead this one, but we will soon promote all the changes here as well. So that you will be able to use just vanilla mkl-dnn. 

P.S. dst_simd_iter (= %rcx) was an unused variable, so everything should be fine with bnorm
