### ISSUE TITLE
Transposed convolution

### ISSUE THREAD

**Issue by mkamrao** [01org/mkl-dnn#141]
Hello

Is the convolution_backward descriptor same as "Transposed Convolution 2D"?

Thank you
kamrao

**Comment by emfomenk** [comment]
Hi @mkamrao,

Haven't heard about transposed convolution. :)
I quickly went through this [Theano documentation](http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html#transposed-convolution).
According to it -- backward convolution is the same as transposed convolution.

> ## Transposed convolution
> ...
> ### Note
> The transposed convolution operation can be thought of as the gradient of some convolution with respect to its input, which is usually how transposed convolutions are implemented in practice.
...
