### ISSUE TITLE
mkl-dnn engine crash on cpu without avx2 support

### ISSUE THREAD

**Issue by etaf** [01org/mkl-dnn#15]
It's known that the mkl-dnn engine not support machines without avx2.
But the engine will crash with "illegal instruction“.
Users will not happy to see the program crash.

Rather than crash, should the engine  still work on  machine without  avx2 support ?
Maybe use other instruction set instead of avx2 when no avx2 support ?

**Comment by rsdubtso** [comment]
You are right, mkl-dnn should not crash on cpus w/o avx2. There is already a patch in the queue that fixes this. It will be pushed to github soon.

**Comment by etaf** [comment]
Thanks for your answer.
