### ISSUE TITLE
failing convolution_backward_weights test

### ISSUE THREAD

**Issue by boegel** [01org/mkl-dnn#151]
### Description

`convolution_backward_weights` test fails, other tests pass.

```
$ make test
...
Start 28: test_convolution_backward_weights
Test #28: test_convolution_backward_weights ..........***Failed  122.30 sec

96% tests passed, 1 tests failed out of 28
```

### Environment

* Intel(R) Xeon(R) CPU E5-2670
  * compiler flags:
    * `-O2 -ftz -fp-speculation=safe -fp-model source -xHost`, or
    * `-O1 -fp-model precise`
* CentOS 7.4
* Intel compilers 2017.4.196 (on top of GCC 6.4.0)
* Intel MKL 2017.3.196
* CMake 3.9.5

### Steps to reproduce

Build mkl-dnn 0.11 on top of (full) Intel MKL 2017.3.196 (i.e. without running `prepare_mkl.sh` to pull in the Intel MKL small libraries).

### Actual behavior

`test_convolution_backward_weights` fails

Output from `Testing/Temporary/LastTest.log`:

```
28/28 Testing: test_convolution_backward_weights
28/28 Test: test_convolution_backward_weights
Command: "/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/easybuild_obj/tests/gtests/test_convolution_backward_weights"
Directory: /tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/easybuild_obj/tests/gtests
"test_convolution_backward_weights" start time: Nov 11 16:58 CET
Output:
----------------------------------------------------------
[==========] Running 95 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from BackwardWeights_SimpleSmall_NCHW/convolution_test
[ RUN      ] BackwardWeights_SimpleSmall_NCHW/convolution_test.TestConvolution/0
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.74987930059432983, which exceeds (data_t)1e-4, where
e evaluates to -0.74987930059432983,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 4 Total: 6
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.74752283096313477, which exceeds (data_t)1e-4, where
e evaluates to -0.74752283096313477,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 5 Total: 6
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.74693089723587036, which exceeds (data_t)1e-4, where
e evaluates to -0.74693089723587036,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 0 Total: 6
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.74829316139221191, which exceeds (data_t)1e-4, where
e evaluates to -0.74829316139221191,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 2 Total: 6
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.75396615266799927, which exceeds (data_t)1e-4, where
e evaluates to -0.75396615266799927,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 1 Total: 6
/tmp/vsc40023/easybuild_build/mkldnn/0.11/intel-2017b/mkl-dnn-0.11/tests/gtests/mkldnn_test_common.hpp:245: Failure
The difference between e and (data_t)0.0 is 0.7509617805480957, which exceeds (data_t)1e-4, where
e evaluates to -0.7509617805480957,
(data_t)0.0 evaluates to 0, and
(data_t)1e-4 evaluates to 9.9999997473787516e-05.
Index: 3 Total: 6
[  FAILED  ] BackwardWeights_SimpleSmall_NCHW/convolution_test.TestConvolution/0, where GetParam() = 92-byte object <01-00 00-00 01-00 00-00 00-00 00-00 05-00 00-00 0C-00 00-00 03-00 00-00 05-00 00-00 02-00 00-00 01-00 00-00 04-00 00-00 04-00 00-00 04-00 00-00 06-00 00-00 04-00 00-00 04-00 00-00 03-00 00-00 03-00 00-00 01-00 00-00 01-00 00-00 01-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00> (170 ms)
```

### Expected behavior

`test_convolution_backward_weights` passes just like other tests

**Comment by emfomenk** [comment]
Hi @boegel,

I cannot reproduce the problem on my side...
Could you please specify the exact commit hash (if it is not v0.11 release), the number of threads used?
Also could you please specify what were the exact compiler flags?
I see you added `-O1 ...`. Did you suppress `-xHOST` option?

**Comment by emfomenk** [comment]
Hmm, I beg your pardon.
Removing `-xHOST` actually reveals the problem.
Will look into that.

**Comment by boegel** [comment]
@emfomenk I see the problem both with using `-O2 -ftz -fp-speculation=safe -fp-model source -xHost` as compilation flags, and also with `-O1 -fp-model precise` (i.e. without `xHost`).
This is done by via `cmake -DCMAKE_CXX_FLAGS="-O1 -fp-model precise" ...` for example.

I'm using the official `v0.11` release, i.e. commit  ba482ec.

**Comment by emfomenk** [comment]
Hi @boegel,

While we have some problems on promoting the fixes to the master branch here, could you please confirm that [this commit](https://github.com/emfomenk/mkl-dnn/commit/cb3253fb8b28ed1db02fa3b740ee8214dbbbc8e2) fixes your problem? You can just use my [mkl-dnn clone](https://github.com/emfomenk/mkl-dnn).

**Comment by boegel** [comment]
@emfomenk I tried building the `mkl-dnn` 0.11 release with (only) the change in cb3253fb8b28ed1db02fa3b740ee8214dbbbc8e2 applied on top of it, and this does indeed fix the problem I was seeing, no more failing tests!

See https://github.com/easybuilders/easybuild-easyconfigs/pull/5362.

**Comment by emfomenk** [comment]
Thanks for confirmation!
We will soon promote all the fixes to the master branch.
