### ISSUE TITLE
convolution forward

### ISSUE THREAD

**Issue by kriszhangyf** [01org/mkl-dnn#155]
Current as i see convolution forward only supports padding left and padding right.
How to handle padding top and padding bottom?

**Comment by emfomenk** [comment]
Hi @kriszhangyf,

Yeah, probably this thing is not very clear in our API...
So convolution descriptor has `mkldnn_dims_t padding[2];` field, which is basically `int padding[2][MAX_DIMS]`.
For 2D convolution:
- padding[0][0] -- is a top padding (aka 'left' padding for the height)
- padding[0][1] -- is a left padding (aka 'left' padding for the width)
- padding[1][0] -- is a bottom padding (aka 'right' padding for the height)
- padding[1][1] -- is a right padding (aka 'right' padding for the height)

**Comment by emfomenk** [comment]
Closing the issue.
Please let me know if you need any further clarification on padding stuff.
