### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by attaullah** [01org/mkl-dnn#159]
### download not working
When I run prepare_mkl.sh, it does not downloads

**Comment by emfomenk** [comment]
Could you please provide more detailed information, like OS, what line causes failure, etc...

If this is Linux, could you please run it like:
```
$ bash -x prepare_mkl.sh
```
to see what exactly goes wrong.

**Comment by vpirogov** [comment]
I'm closing this issue as we have no way to reproduce it. Feel free to reopen with additional details.
