### ISSUE TITLE
build intel-caffe with latest mkl-dnn failed, older mkl-dnn successed

### ISSUE THREAD

**Issue by etaf** [01org/mkl-dnn#16]
I builded intel caffe successed wilth mkl-dnn(commit: 47bda9503f669c0e08ac84fea3f6e7aa05991b72).
But failed on latest commit, have you tested that ?

**Comment by rsdubtso** [comment]
This probably needs to be filed against intel caffe (https://github.com/intel/caffe). Two teams are collaborating on the mkl-dnn support, but the library changes faster than the support code in the framework.

Can I summon @jreniecki into this thread?

**Comment by rsdubtso** [comment]
Also, let me try reproducing this on my end. Maybe there's a quick fix we can make to resolve this.

**Comment by rsdubtso** [comment]
Okay. The build fails due to the change in the batch normalization API. This is a known issue, and the update to the intelcaffe is in the works. I'm inclined to close this issue since there's nothing we can do in the mkl-dnn source code to fix it.

**Comment by etaf** [comment]
Thanks for your help.
