### ISSUE TITLE
intel caffe fails with latest mkldnn

### ISSUE THREAD

**Issue by sfraczek** [01org/mkl-dnn#162]
due to -Werror flag I cannot build caffe with mkldnn. It spits:

root/caffe/external/mkldnn/src/src/cpu/jit_avx512_common_conv_kernel.cpp: In lambda function:
/root/caffe/external/mkldnn/src/src/cpu/jit_avx512_common_conv_kernel.cpp:2666:42: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     auto emit_fma_block = [&](int kh_step) {
                                          ^
cc1plus: all warnings being treated as errors

**Comment by sfraczek** [comment]
It doesn't. Thanks, I added this manually. Do you know if the (new) caffe team is aware of this issue?

**Comment by emfomenk** [comment]
I am not sure, you may want to ask them on IntelCaffe forum.
But I think they are about to make a new release, and it would include one of the latest MKL-DNN with the fix.
