### ISSUE TITLE
Make pycaffe results in error during install

### ISSUE THREAD

**Issue by shardulgo** [01org/mkl-dnn#163]
### Description
Installing intelcaffe on a brand new system.  Installed MKL & OpenCV with no issues.  Went thru instructions to intel caffe and entered "make pycaffe" resulting in error below:

<img width="584" alt="error" src="https://user-images.githubusercontent.com/18713351/33742290-824148aa-db5c-11e7-9822-0752dc13a6b1.PNG">

### Environment
Ubuntu 16.04 LTS

**Comment by rsdubtso** [comment]
Seems really familiar... #146
Could you please double check that yours MKL-DNN has this commit 2604f43?

**Comment by shardulgo** [comment]
I figured it out.  It's a known issue with Caffe 1.0.6, so I downgraded to Caffe 1.0.5 and it worked fine.  Install worked well and mkl install worked too. 

Not sure what the fix is to the above aside from downgrading Caffe versions, but temporary workaround is to downgrade Caffe and reinstall. Closing issue.
