### ISSUE TITLE
A clarification about the release build

### ISSUE THREAD

**Issue by masahi** [01org/mkl-dnn#165]
Hi, I want to know some details about the release builds available [here](https://github.com/01org/mkl-dnn/releases) . My understanding is that they are not built from this open source mkl-dnn library. Are they subsets of the proprietary MKL library?

**Comment by vpirogov** [comment]
That's correct, these binaries are a subset of Intel MKL that may be used in Intel MKL-DNN to get fast sgemm. These binaries are also used by some of deep learning frameworks to get certain optimized functionality. We do not release pre-built Intel MKL-DNN.

**Comment by masahi** [comment]
Thanks. I'm using the v0.11 release build with MXNet on windows.  I believe there are some memory usage issues in MKLML itself or the way MXNet uses MKLML. In my testing, the VGG16 network, when given a input batch of size (1, 1, 256, 256), requires more than 15G of CPU memory. Falling back to MXNet's CPU convolution implementation solved the memory issue.

It is probably not the right place to ask, but are there known memory issues in MKLML? If not, then it is certainly MXNet's problem and I'll ask them.

**Comment by rsdubtso** [comment]
I am not aware of any. Are you sure they are coming from MKL and not MKL-DNN? I thought that MXNet also supports the latter... Which CPU you are running on?

**Comment by ykim362** [comment]
@masahi when mkl or mkl-dnn is utilized in mxnet, it allocate some additional memory to get the best performance. This issue will be resolved in the future software release which is under active development. It will be released soon in the mxnet master branch.

**Comment by ykim362** [comment]
@masahi if you are building mxnet from the source code, one option you can try is turning off USE_MKL2017_EXPERIMENTAL in the config.mk file. That might be a little slower but uses the same amount of memory as default cpu.

**Comment by masahi** [comment]
@rsdubtso the open source MKL-DNN has not been integrated into MXNet yet, but the PR is ongoing at apache/incubator-mxnet#8302. The issue happens when using the conv op from MKL. I don't know if it is a MKL or MXNet problem. 

@ykim362 OK, I'll try building without USE_MKL2017_EXPERIMENTAL. I'm very much looking forward to better MKL or MKL-DNN integration into MXNet. Thanks.
