### ISSUE TITLE
Pooling indices

### ISSUE THREAD

**Issue by xyzsam** [01org/mkl-dnn#169]
What is the purpose of the pooling indices parameter in `pooling_forward`? They are presented as an seemingly optional additional output of pooling layers, but I don't know what they're supposed to represent, and if I try to not use that parameter, MKL-DNN throws an error when creating the primitive. It's probably because the constructor that omits the `workspace` memory fills in a null pointer in its place and that gets caught as an error during primitive construction.

**Comment by xyzsam** [comment]
Never mind - pooling indices are kept around for the backwards pass. Forgot about that...

But the question about not using them still remains - if we only care about the forward pass, we shouldn't need to keep them around.

**Comment by vpirogov** [comment]
Glad you have the part about backprop figured out. If you want to run inference (only the forward pass without the backward) then you need to create primitive descriptor with `prop_kind::forward_inference`. See an [inference example here](https://github.com/adhere/For_MKL_DNN_issue/blob/master/simple_net.cpp).

**Comment by xyzsam** [comment]
Thanks, fixed the issue.
