### ISSUE TITLE
Test code for 2D convolution, accumulation over the input channels - bug?

### ISSUE THREAD

**Issue by amathuri** [01org/mkl-dnn#173]
Hi,
If I understand the following test for 2D Convolution correctly, then both the input and output channels are blocked with g (groups?) dimension. In the process of 2D convolution, the dot product happens over all the input channels. But, I don't see accumulation happening over g dimension. That, would mean that the dot product would only occur over "c.ic / c.ng" channels.

https://github.com/01org/mkl-dnn/blob/ede1e332a0d32cbac02f5522334e6128e7d6988e/tests/gtests/test_convolution_forward_common.hpp#L56

Is this a bug? If not, then can you please exaplain?

**Comment by emfomenk** [comment]
Hi @amathuri,

This in not a bug -- it fully corresponds to the definition of the grouped convolution.
See [this](http://caffe.berkeleyvision.org/tutorial/layers/convolution.html) and [this](https://blog.yani.io/filter-group-tutorial/) for more information.

**Comment by amathuri** [comment]
Thank you for the pointers. This explains it!
