### ISSUE TITLE
Possibly incorrect argument.

### ISSUE THREAD

**Issue by kruus** [01org/mkl-dnn#174]
### Warning (unused variable) if using cblas.
Should the call to [cblas_sgemm](https://github.com/01org/mkl-dnn/blob/ede1e332a0d32cbac02f5522334e6128e7d6988e/src/cpu/gemm_convolution.cpp#L100) use ***beta**, instead of **zero**, to match the sgemm call?

**Comment by emfomenk** [comment]
Hi @kruus,

Good to hear from you!
Will take a look. So far seems like a bug indeed.
