### ISSUE TITLE
Corner case crash when batch size of tensor is 0

### ISSUE THREAD

**Issue by 4pao** [01org/mkl-dnn#175]
### Description
There is a test case created a memory shape like (0, 16, 8, 8), then MKL-DNN will crash at nd_iterator_init (in reorder or other primitives). Quick fix would be compare start and end and found out there was nothing to calculate and then bailout earlier or fix nd_iterator_init to skip mode 0.

I know this is very rare and probability never happen in real situation, however change testcase of a framework seems also a bad option.

### Environment
Linux/OS X, general

### Steps to reproduce
reorder from a(0, 16, 8, 8) to b (0, 16, 8, 8).

### Actual behavior
Crash in nd_iterator_init

### Expected behavior
Nothing happen and finish sucessfully

**Comment by rsdubtso** [comment]
This is kind of embarrassing... Thanks for the report!

**Comment by rsdubtso** [comment]
Which formats you are converting from / to and which compiler and MKL-DNN version do you use? I can make MKL-DNN fail when converting nhwc to chwn with icc but the backtrace does not point me to nd_iterator_init().

**Comment by 4pao** [comment]
Oh I see, you go to the ref.

Mine: Reorder from nchw to nchw. homebrew llvm/clang 5.0, direct_copy except dim0.

It seems my ref path is good even on Linux with icpc-18 or gcc.
