### ISSUE TITLE
Unable to run basic test suite of 32 tests

### ISSUE THREAD

**Issue by mrinmayk** [01org/mkl-dnn#178]
### Description
I am unable to run the basic test suite as it is not finding the executables for the different tests on doing "make test" inside build directory.

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:
CPU make and model (try lscpu)
2.5 Ghz Core i5
4GB 1600 Mhz DDR3

OS version (uname -a)
Darwin Mrinmays-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov 9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Compiler version (gcc --version)
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

MKLROOT value (echo MKLROOT=$MKLROOT)
(Blank/empty)

CMake version (cmake --version)
3.10.1

CMake output log

### Steps to reproduce
As mentioned

### Actual behavior

Output of command prompt is:- 

Mrinmays-MacBook-Pro:build mrinmaykalita$ make test

Running tests...

Test project /Users/mrinmaykalita/Downloads/mkl-dnn-master/build

      Start  1: simple-net-c

Could not find executable simple-net-c

Looked in the following places:

simple-net-c

simple-net-c

Release/simple-net-c

Release/simple-net-c

Debug/simple-net-c

Debug/simple-net-c

MinSizeRel/simple-net-c

MinSizeRel/simple-net-c

RelWithDebInfo/simple-net-c

RelWithDebInfo/simple-net-c

Deployment/simple-net-c

Deployment/simple-net-c

Development/simple-net-c

Development/simple-net-c

Unable to find executable: simple-net-c

 1/32 Test  #1: simple-net-c ...............................***Not Run   0.00 sec

      Start  2: simple-net-cpp

Could not find executable simple-net-cpp

Looked in the following places:

simple-net-cpp

simple-net-cpp

Release/simple-net-cpp

Release/simple-net-cpp

Debug/simple-net-cpp

Debug/simple-net-cpp

MinSizeRel/simple-net-cpp

MinSizeRel/simple-net-cpp

RelWithDebInfo/simple-net-cpp

RelWithDebInfo/simple-net-cpp

Deployment/simple-net-cpp

Deployment/simple-net-cpp

Development/simple-net-cpp

Development/simple-net-cpp

Unable to find executable: simple-net-cpp

 2/32 Test  #2: simple-net-cpp .............................***Not Run   0.00 sec

      Start  3: simple-training-net-c

Could not find executable simple-training-net-c

Looked in the following places:

simple-training-net-c

simple-training-net-c

Release/simple-training-net-c

Release/simple-training-net-c

Debug/simple-training-net-c

Debug/simple-training-net-c

MinSizeRel/simple-training-net-c

MinSizeRel/simple-training-net-c

RelWithDebInfo/simple-training-net-c

RelWithDebInfo/simple-training-net-c

Deployment/simple-training-net-c

Deployment/simple-training-net-c

Development/simple-training-net-c

Development/simple-training-net-c

Unable to find executable: simple-training-net-c

 3/32 Test  #3: simple-training-net-c ......................***Not Run   0.00 sec

      Start  4: simple-training-net-cpp

Could not find executable simple-training-net-cpp

Looked in the following places:

simple-training-net-cpp

simple-training-net-cpp

Release/simple-training-net-cpp

Release/simple-training-net-cpp

Debug/simple-training-net-cpp

Debug/simple-training-net-cpp

MinSizeRel/simple-training-net-cpp

MinSizeRel/simple-training-net-cpp

RelWithDebInfo/simple-training-net-cpp

RelWithDebInfo/simple-training-net-cpp

Deployment/simple-training-net-cpp

Deployment/simple-training-net-cpp

Development/simple-training-net-cpp

Development/simple-training-net-cpp

Unable to find executable: simple-training-net-cpp

 4/32 Test  #4: simple-training-net-cpp ....................***Not Run   0.00 sec

      Start  5: api-c

Could not find executable api-c

Looked in the following places:

api-c

api-c

Release/api-c

Release/api-c

Debug/api-c

Debug/api-c

MinSizeRel/api-c

MinSizeRel/api-c

RelWithDebInfo/api-c

RelWithDebInfo/api-c

Deployment/api-c

Deployment/api-c

Development/api-c

Development/api-c

Unable to find executable: api-c

 5/32 Test  #5: api-c ......................................***Not Run   0.00 sec

      Start  6: test_c_symbols-c

Could not find executable test_c_symbols-c

Looked in the following places:

test_c_symbols-c

test_c_symbols-c

Release/test_c_symbols-c

Release/test_c_symbols-c

Debug/test_c_symbols-c

Debug/test_c_symbols-c

MinSizeRel/test_c_symbols-c

MinSizeRel/test_c_symbols-c

RelWithDebInfo/test_c_symbols-c

RelWithDebInfo/test_c_symbols-c

Deployment/test_c_symbols-c

Deployment/test_c_symbols-c

Development/test_c_symbols-c

Development/test_c_symbols-c

Unable to find executable: test_c_symbols-c

 6/32 Test  #6: test_c_symbols-c ...........................***Not Run   0.00 sec

      Start  7: test_iface_pd_iter

Could not find executable test_iface_pd_iter

Looked in the following places:

test_iface_pd_iter

test_iface_pd_iter

Release/test_iface_pd_iter

Release/test_iface_pd_iter

Debug/test_iface_pd_iter

Debug/test_iface_pd_iter

MinSizeRel/test_iface_pd_iter

MinSizeRel/test_iface_pd_iter

RelWithDebInfo/test_iface_pd_iter

RelWithDebInfo/test_iface_pd_iter

Deployment/test_iface_pd_iter

Deployment/test_iface_pd_iter

Development/test_iface_pd_iter

Development/test_iface_pd_iter

Unable to find executable: test_iface_pd_iter

 7/32 Test  #7: test_iface_pd_iter .........................***Not Run   0.00 sec

      Start  8: test_iface_attr

Could not find executable test_iface_attr

Looked in the following places:

test_iface_attr

test_iface_attr

Release/test_iface_attr

Release/test_iface_attr

Debug/test_iface_attr

Debug/test_iface_attr

MinSizeRel/test_iface_attr

MinSizeRel/test_iface_attr

RelWithDebInfo/test_iface_attr

RelWithDebInfo/test_iface_attr

Deployment/test_iface_attr

Deployment/test_iface_attr

Development/test_iface_attr

Development/test_iface_attr

Unable to find executable: test_iface_attr

 8/32 Test  #8: test_iface_attr ............................***Not Run   0.00 sec

      Start  9: test_sum

Could not find executable test_sum

Looked in the following places:

test_sum

test_sum

Release/test_sum

Release/test_sum

Debug/test_sum

Debug/test_sum

MinSizeRel/test_sum

MinSizeRel/test_sum

RelWithDebInfo/test_sum

RelWithDebInfo/test_sum

Deployment/test_sum

Deployment/test_sum

Development/test_sum

Development/test_sum

Unable to find executable: test_sum

 9/32 Test  #9: test_sum ...................................***Not Run   0.00 sec

      Start 10: test_reorder

Could not find executable test_reorder

Looked in the following places:

test_reorder

test_reorder

Release/test_reorder

Release/test_reorder

Debug/test_reorder

Debug/test_reorder

MinSizeRel/test_reorder

MinSizeRel/test_reorder

RelWithDebInfo/test_reorder

RelWithDebInfo/test_reorder

Deployment/test_reorder

Deployment/test_reorder

Development/test_reorder

Development/test_reorder

Unable to find executable: test_reorder

10/32 Test #10: test_reorder ...............................***Not Run   0.00 sec

      Start 11: test_concat

Could not find executable test_concat

Looked in the following places:

test_concat

test_concat

Release/test_concat

Release/test_concat

Debug/test_concat

Debug/test_concat

MinSizeRel/test_concat

MinSizeRel/test_concat

RelWithDebInfo/test_concat

RelWithDebInfo/test_concat

Deployment/test_concat

Deployment/test_concat

Development/test_concat

Development/test_concat

Unable to find executable: test_concat

11/32 Test #11: test_concat ................................***Not Run   0.00 sec

      Start 12: test_softmax_forward

Could not find executable test_softmax_forward

Looked in the following places:

test_softmax_forward

test_softmax_forward

Release/test_softmax_forward

Release/test_softmax_forward

Debug/test_softmax_forward

Debug/test_softmax_forward

MinSizeRel/test_softmax_forward

MinSizeRel/test_softmax_forward

RelWithDebInfo/test_softmax_forward

RelWithDebInfo/test_softmax_forward

Deployment/test_softmax_forward

Deployment/test_softmax_forward

Development/test_softmax_forward

Development/test_softmax_forward

Unable to find executable: test_softmax_forward

12/32 Test #12: test_softmax_forward .......................***Not Run   0.00 sec

      Start 13: test_eltwise

Could not find executable test_eltwise

Looked in the following places:

test_eltwise

test_eltwise

Release/test_eltwise

Release/test_eltwise

Debug/test_eltwise

Debug/test_eltwise

MinSizeRel/test_eltwise

MinSizeRel/test_eltwise

RelWithDebInfo/test_eltwise

RelWithDebInfo/test_eltwise

Deployment/test_eltwise

Deployment/test_eltwise

Development/test_eltwise

Development/test_eltwise

Unable to find executable: test_eltwise

13/32 Test #13: test_eltwise ...............................***Not Run   0.00 sec

      Start 14: test_relu

Could not find executable test_relu

Looked in the following places:

test_relu

test_relu

Release/test_relu

Release/test_relu

Debug/test_relu

Debug/test_relu

MinSizeRel/test_relu

MinSizeRel/test_relu

RelWithDebInfo/test_relu

RelWithDebInfo/test_relu

Deployment/test_relu

Deployment/test_relu

Development/test_relu

Development/test_relu

Unable to find executable: test_relu

14/32 Test #14: test_relu ..................................***Not Run   0.00 sec

      Start 15: test_lrn_forward

Could not find executable test_lrn_forward

Looked in the following places:

test_lrn_forward

test_lrn_forward

Release/test_lrn_forward

Release/test_lrn_forward

Debug/test_lrn_forward

Debug/test_lrn_forward

MinSizeRel/test_lrn_forward

MinSizeRel/test_lrn_forward

RelWithDebInfo/test_lrn_forward

RelWithDebInfo/test_lrn_forward

Deployment/test_lrn_forward

Deployment/test_lrn_forward

Development/test_lrn_forward

Development/test_lrn_forward

Unable to find executable: test_lrn_forward

15/32 Test #15: test_lrn_forward ...........................***Not Run   0.00 sec

      Start 16: test_lrn_backward

Could not find executable test_lrn_backward

Looked in the following places:

test_lrn_backward

test_lrn_backward

Release/test_lrn_backward

Release/test_lrn_backward

Debug/test_lrn_backward

Debug/test_lrn_backward

MinSizeRel/test_lrn_backward

MinSizeRel/test_lrn_backward

RelWithDebInfo/test_lrn_backward

RelWithDebInfo/test_lrn_backward

Deployment/test_lrn_backward

Deployment/test_lrn_backward

Development/test_lrn_backward

Development/test_lrn_backward

Unable to find executable: test_lrn_backward

16/32 Test #16: test_lrn_backward ..........................***Not Run   0.00 sec

      Start 17: test_pooling_forward

Could not find executable test_pooling_forward

Looked in the following places:

test_pooling_forward

test_pooling_forward

Release/test_pooling_forward

Release/test_pooling_forward

Debug/test_pooling_forward

Debug/test_pooling_forward

MinSizeRel/test_pooling_forward

MinSizeRel/test_pooling_forward

RelWithDebInfo/test_pooling_forward

RelWithDebInfo/test_pooling_forward

Deployment/test_pooling_forward

Deployment/test_pooling_forward

Development/test_pooling_forward

Development/test_pooling_forward

Unable to find executable: test_pooling_forward

17/32 Test #17: test_pooling_forward .......................***Not Run   0.00 sec

      Start 18: test_pooling_backward

Could not find executable test_pooling_backward

Looked in the following places:

test_pooling_backward

test_pooling_backward

Release/test_pooling_backward

Release/test_pooling_backward

Debug/test_pooling_backward

Debug/test_pooling_backward

MinSizeRel/test_pooling_backward

MinSizeRel/test_pooling_backward

RelWithDebInfo/test_pooling_backward

RelWithDebInfo/test_pooling_backward

Deployment/test_pooling_backward

Deployment/test_pooling_backward

Development/test_pooling_backward

Development/test_pooling_backward

Unable to find executable: test_pooling_backward

18/32 Test #18: test_pooling_backward ......................***Not Run   0.00 sec

      Start 19: test_batch_normalization

Could not find executable test_batch_normalization

Looked in the following places:

test_batch_normalization

test_batch_normalization

Release/test_batch_normalization

Release/test_batch_normalization

Debug/test_batch_normalization

Debug/test_batch_normalization

MinSizeRel/test_batch_normalization

MinSizeRel/test_batch_normalization

RelWithDebInfo/test_batch_normalization

RelWithDebInfo/test_batch_normalization

Deployment/test_batch_normalization

Deployment/test_batch_normalization

Development/test_batch_normalization

Development/test_batch_normalization

Unable to find executable: test_batch_normalization

19/32 Test #19: test_batch_normalization ...................***Not Run   0.00 sec

      Start 20: test_inner_product_forward

Could not find executable test_inner_product_forward

Looked in the following places:

test_inner_product_forward

test_inner_product_forward

Release/test_inner_product_forward

Release/test_inner_product_forward

Debug/test_inner_product_forward

Debug/test_inner_product_forward

MinSizeRel/test_inner_product_forward

MinSizeRel/test_inner_product_forward

RelWithDebInfo/test_inner_product_forward

RelWithDebInfo/test_inner_product_forward

Deployment/test_inner_product_forward

Deployment/test_inner_product_forward

Development/test_inner_product_forward

Development/test_inner_product_forward

Unable to find executable: test_inner_product_forward

20/32 Test #20: test_inner_product_forward .................***Not Run   0.00 sec

      Start 21: test_inner_product_backward_data

Could not find executable test_inner_product_backward_data

Looked in the following places:

test_inner_product_backward_data

test_inner_product_backward_data

Release/test_inner_product_backward_data

Release/test_inner_product_backward_data

Debug/test_inner_product_backward_data

Debug/test_inner_product_backward_data

MinSizeRel/test_inner_product_backward_data

MinSizeRel/test_inner_product_backward_data

RelWithDebInfo/test_inner_product_backward_data

RelWithDebInfo/test_inner_product_backward_data

Deployment/test_inner_product_backward_data

Deployment/test_inner_product_backward_data

Development/test_inner_product_backward_data

Development/test_inner_product_backward_data

Unable to find executable: test_inner_product_backward_data

21/32 Test #21: test_inner_product_backward_data ...........***Not Run   0.00 sec

      Start 22: test_inner_product_backward_weights

Could not find executable test_inner_product_backward_weights

Looked in the following places:

test_inner_product_backward_weights

test_inner_product_backward_weights

Release/test_inner_product_backward_weights

Release/test_inner_product_backward_weights

Debug/test_inner_product_backward_weights

Debug/test_inner_product_backward_weights

MinSizeRel/test_inner_product_backward_weights

MinSizeRel/test_inner_product_backward_weights

RelWithDebInfo/test_inner_product_backward_weights

RelWithDebInfo/test_inner_product_backward_weights

Deployment/test_inner_product_backward_weights

Deployment/test_inner_product_backward_weights

Development/test_inner_product_backward_weights

Development/test_inner_product_backward_weights

Unable to find executable: test_inner_product_backward_weights

22/32 Test #22: test_inner_product_backward_weights ........***Not Run   0.00 sec

      Start 23: test_convolution_format_any

Could not find executable test_convolution_format_any

Looked in the following places:

test_convolution_format_any

test_convolution_format_any

Release/test_convolution_format_any

Release/test_convolution_format_any

Debug/test_convolution_format_any

Debug/test_convolution_format_any

MinSizeRel/test_convolution_format_any

MinSizeRel/test_convolution_format_any

RelWithDebInfo/test_convolution_format_any

RelWithDebInfo/test_convolution_format_any

Deployment/test_convolution_format_any

Deployment/test_convolution_format_any

Development/test_convolution_format_any

Development/test_convolution_format_any

Unable to find executable: test_convolution_format_any

23/32 Test #23: test_convolution_format_any ................***Not Run   0.00 sec

      Start 24: test_convolution_forward_f32

Could not find executable test_convolution_forward_f32

Looked in the following places:

test_convolution_forward_f32

test_convolution_forward_f32

Release/test_convolution_forward_f32

Release/test_convolution_forward_f32

Debug/test_convolution_forward_f32

Debug/test_convolution_forward_f32

MinSizeRel/test_convolution_forward_f32

MinSizeRel/test_convolution_forward_f32

RelWithDebInfo/test_convolution_forward_f32

RelWithDebInfo/test_convolution_forward_f32

Deployment/test_convolution_forward_f32

Deployment/test_convolution_forward_f32

Development/test_convolution_forward_f32

Development/test_convolution_forward_f32

Unable to find executable: test_convolution_forward_f32

24/32 Test #24: test_convolution_forward_f32 ...............***Not Run   0.00 sec

      Start 25: test_convolution_forward_s16s16s32

Could not find executable test_convolution_forward_s16s16s32

Looked in the following places:

test_convolution_forward_s16s16s32

test_convolution_forward_s16s16s32

Release/test_convolution_forward_s16s16s32

Release/test_convolution_forward_s16s16s32

Debug/test_convolution_forward_s16s16s32

Debug/test_convolution_forward_s16s16s32

MinSizeRel/test_convolution_forward_s16s16s32

MinSizeRel/test_convolution_forward_s16s16s32

RelWithDebInfo/test_convolution_forward_s16s16s32

RelWithDebInfo/test_convolution_forward_s16s16s32

Deployment/test_convolution_forward_s16s16s32

Deployment/test_convolution_forward_s16s16s32

Development/test_convolution_forward_s16s16s32

Development/test_convolution_forward_s16s16s32

Unable to find executable: test_convolution_forward_s16s16s32

25/32 Test #25: test_convolution_forward_s16s16s32 .........***Not Run   0.00 sec

      Start 26: test_convolution_forward_u8s8s32

Could not find executable test_convolution_forward_u8s8s32

Looked in the following places:

test_convolution_forward_u8s8s32

test_convolution_forward_u8s8s32

Release/test_convolution_forward_u8s8s32

Release/test_convolution_forward_u8s8s32

Debug/test_convolution_forward_u8s8s32

Debug/test_convolution_forward_u8s8s32

MinSizeRel/test_convolution_forward_u8s8s32

MinSizeRel/test_convolution_forward_u8s8s32

RelWithDebInfo/test_convolution_forward_u8s8s32

RelWithDebInfo/test_convolution_forward_u8s8s32

Deployment/test_convolution_forward_u8s8s32

Deployment/test_convolution_forward_u8s8s32

Development/test_convolution_forward_u8s8s32

Development/test_convolution_forward_u8s8s32

Unable to find executable: test_convolution_forward_u8s8s32

26/32 Test #26: test_convolution_forward_u8s8s32 ...........***Not Run   0.00 sec

      Start 27: test_convolution_forward_u8s8fp

Could not find executable test_convolution_forward_u8s8fp

Looked in the following places:

test_convolution_forward_u8s8fp

test_convolution_forward_u8s8fp

Release/test_convolution_forward_u8s8fp

Release/test_convolution_forward_u8s8fp

Debug/test_convolution_forward_u8s8fp

Debug/test_convolution_forward_u8s8fp

MinSizeRel/test_convolution_forward_u8s8fp

MinSizeRel/test_convolution_forward_u8s8fp

RelWithDebInfo/test_convolution_forward_u8s8fp

RelWithDebInfo/test_convolution_forward_u8s8fp

Deployment/test_convolution_forward_u8s8fp

Deployment/test_convolution_forward_u8s8fp

Development/test_convolution_forward_u8s8fp

Development/test_convolution_forward_u8s8fp

Unable to find executable: test_convolution_forward_u8s8fp

27/32 Test #27: test_convolution_forward_u8s8fp ............***Not Run   0.00 sec

      Start 28: test_convolution_relu_forward_f32

Could not find executable test_convolution_relu_forward_f32

Looked in the following places:

test_convolution_relu_forward_f32

test_convolution_relu_forward_f32

Release/test_convolution_relu_forward_f32

Release/test_convolution_relu_forward_f32

Debug/test_convolution_relu_forward_f32

Debug/test_convolution_relu_forward_f32

MinSizeRel/test_convolution_relu_forward_f32

MinSizeRel/test_convolution_relu_forward_f32

RelWithDebInfo/test_convolution_relu_forward_f32

RelWithDebInfo/test_convolution_relu_forward_f32

Deployment/test_convolution_relu_forward_f32

Deployment/test_convolution_relu_forward_f32

Development/test_convolution_relu_forward_f32

Development/test_convolution_relu_forward_f32

Unable to find executable: test_convolution_relu_forward_f32

28/32 Test #28: test_convolution_relu_forward_f32 ..........***Not Run   0.00 sec

      Start 29: test_convolution_relu_forward_s16s16s32

Could not find executable test_convolution_relu_forward_s16s16s32

Looked in the following places:

test_convolution_relu_forward_s16s16s32

test_convolution_relu_forward_s16s16s32

Release/test_convolution_relu_forward_s16s16s32

Release/test_convolution_relu_forward_s16s16s32

Debug/test_convolution_relu_forward_s16s16s32

Debug/test_convolution_relu_forward_s16s16s32

MinSizeRel/test_convolution_relu_forward_s16s16s32

MinSizeRel/test_convolution_relu_forward_s16s16s32

RelWithDebInfo/test_convolution_relu_forward_s16s16s32

RelWithDebInfo/test_convolution_relu_forward_s16s16s32

Deployment/test_convolution_relu_forward_s16s16s32

Deployment/test_convolution_relu_forward_s16s16s32

Development/test_convolution_relu_forward_s16s16s32

Development/test_convolution_relu_forward_s16s16s32

Unable to find executable: test_convolution_relu_forward_s16s16s32

29/32 Test #29: test_convolution_relu_forward_s16s16s32 ....***Not Run   0.00 sec

      Start 30: test_convolution_backward_data_f32

Could not find executable test_convolution_backward_data_f32

Looked in the following places:

test_convolution_backward_data_f32

test_convolution_backward_data_f32

Release/test_convolution_backward_data_f32

Release/test_convolution_backward_data_f32

Debug/test_convolution_backward_data_f32

Debug/test_convolution_backward_data_f32

MinSizeRel/test_convolution_backward_data_f32

MinSizeRel/test_convolution_backward_data_f32

RelWithDebInfo/test_convolution_backward_data_f32

RelWithDebInfo/test_convolution_backward_data_f32

Deployment/test_convolution_backward_data_f32

Deployment/test_convolution_backward_data_f32

Development/test_convolution_backward_data_f32

Development/test_convolution_backward_data_f32

Unable to find executable: test_convolution_backward_data_f32

30/32 Test #30: test_convolution_backward_data_f32 .........***Not Run   0.00 sec

      Start 31: test_convolution_backward_data_s16s16s32

Could not find executable test_convolution_backward_data_s16s16s32

Looked in the following places:

test_convolution_backward_data_s16s16s32

test_convolution_backward_data_s16s16s32

Release/test_convolution_backward_data_s16s16s32

Release/test_convolution_backward_data_s16s16s32

Debug/test_convolution_backward_data_s16s16s32

Debug/test_convolution_backward_data_s16s16s32

MinSizeRel/test_convolution_backward_data_s16s16s32

MinSizeRel/test_convolution_backward_data_s16s16s32

RelWithDebInfo/test_convolution_backward_data_s16s16s32

RelWithDebInfo/test_convolution_backward_data_s16s16s32

Deployment/test_convolution_backward_data_s16s16s32

Deployment/test_convolution_backward_data_s16s16s32

Development/test_convolution_backward_data_s16s16s32

Development/test_convolution_backward_data_s16s16s32

Unable to find executable: test_convolution_backward_data_s16s16s32

31/32 Test #31: test_convolution_backward_data_s16s16s32 ...***Not Run   0.00 sec

      Start 32: test_convolution_backward_weights

Could not find executable test_convolution_backward_weights

Looked in the following places:

test_convolution_backward_weights

test_convolution_backward_weights

Release/test_convolution_backward_weights

Release/test_convolution_backward_weights

Debug/test_convolution_backward_weights

Debug/test_convolution_backward_weights

MinSizeRel/test_convolution_backward_weights

MinSizeRel/test_convolution_backward_weights

RelWithDebInfo/test_convolution_backward_weights

RelWithDebInfo/test_convolution_backward_weights

Deployment/test_convolution_backward_weights

Deployment/test_convolution_backward_weights

Development/test_convolution_backward_weights

Development/test_convolution_backward_weights

Unable to find executable: test_convolution_backward_weights

32/32 Test #32: test_convolution_backward_weights ..........***Not Run   0.00 sec

 

0% tests passed, 32 tests failed out of 32

 

Total Test time (real) =   0.03 sec

 

The following tests FAILED:

  1 - simple-net-c (Not Run)

  2 - simple-net-cpp (Not Run)

  3 - simple-training-net-c (Not Run)

  4 - simple-training-net-cpp (Not Run)

  5 - api-c (Not Run)

  6 - test_c_symbols-c (Not Run)

  7 - test_iface_pd_iter (Not Run)

  8 - test_iface_attr (Not Run)

  9 - test_sum (Not Run)

10 - test_reorder (Not Run)

11 - test_concat (Not Run)

12 - test_softmax_forward (Not Run)

13 - test_eltwise (Not Run)

14 - test_relu (Not Run)

15 - test_lrn_forward (Not Run)

16 - test_lrn_backward (Not Run)

17 - test_pooling_forward (Not Run)

18 - test_pooling_backward (Not Run)

19 - test_batch_normalization (Not Run)

20 - test_inner_product_forward (Not Run)

21 - test_inner_product_backward_data (Not Run)

22 - test_inner_product_backward_weights (Not Run)

23 - test_convolution_format_any (Not Run)

24 - test_convolution_forward_f32 (Not Run)

25 - test_convolution_forward_s16s16s32 (Not Run)

26 - test_convolution_forward_u8s8s32 (Not Run)

27 - test_convolution_forward_u8s8fp (Not Run)

28 - test_convolution_relu_forward_f32 (Not Run)

29 - test_convolution_relu_forward_s16s16s32 (Not Run)

30 - test_convolution_backward_data_f32 (Not Run)

31 - test_convolution_backward_data_s16s16s32 (Not Run)

32 - test_convolution_backward_weights (Not Run)

Errors while running CTest

### Expected behavior
All 32 tests passed so I can finalize installation.

**Comment by vpirogov** [comment]
Intel MKL-DNN is distributed in the source code only and you need to build it before running the tests. Try running `make` before running `make test`.

**Comment by mrinmayk** [comment]
The tests are running now, thanks!.
