### ISSUE TITLE
A minor error in code

### ISSUE THREAD

**Issue by 4pao** [01org/mkl-dnn#184]
### Description
    virtual const memory_pd_t *output_pd(int index = 0) const override
    { switch (index) {
        case 0: return diff_weights_pd(0);
        case 1: [here] with_bias() ? diff_weights_pd(1) : nullptr;
        default: return nullptr;
        }
    }

In file src/common/convolution_pd.hpp:245, Might miss a return there?

**Comment by emfomenk** [comment]
You are absolutely right.
Thanks for submitting an issue.
Will promote the fix soon.
