### ISSUE TITLE
mkl lib for osx?

### ISSUE THREAD

**Issue by gaming-hacker** [01org/mkl-dnn#19]
the script only downloads for linux.  is there an osx version?

**Comment by rsdubtso** [comment]
Are you referring to the script that downloads MKL? We did not test mkl-dnn on OSX so there are probably additional issues. If you already have MKL installed (there is a free version now), you can try using it to with mkl-dnn by setting MKLROOT environment variable. This can be done by, for example, sourcing mklvars.sh setup script.

PS. If you decide to give this a try, please let me know how it went. If there are minor issues, we can try fixing them before we start working on an official OSX support.
