### ISSUE TITLE
when will backprop be supported?

### ISSUE THREAD

**Issue by frankmanbb** [01org/mkl-dnn#2]
It seems currently only forward is supported, when will backprop been supportd?

**Comment by vpirogov** [comment]
You are right, currently the library supports only forward propagation. We are working on extending the API to support backward backward propagation and you'll start seeing commits related to this functionality soon. Stay tuned!

**Comment by vpirogov** [comment]
The latest update includes API support and reference implementation of backward propagation for all supported primitives. This version can be used to integrate backprop functionality and validate it. Now we are focused on adding optimized code.
