### ISSUE TITLE
FC depends on OMP and cblas?

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#20]
Is it possible that fc do not rely on them.
So it is more convenient that we may not be bothered by omp or iomp.

**Comment by rsdubtso** [comment]
1) mkl-dnn uses OpenMP for parallelization. While it should be possible to build it without OpenMP, it is not the target use mode, and the resulting performance will be low.

2) non-GEMM implementation of fully-connected/inner-product is in the works

**Comment by tensor-tang** [comment]
Well, thanks.
But I got an issue that even I use mkl cblas and openmp, still got pretty slow speed on FC, compared with Intelcaffe.
And ldd has both gomp and iomp, also use -Wl,--as-needed -liomp5, and still got this issue, while other layers working well.
Do you have any opinions? 
Thanks.

**Comment by tensor-tang** [comment]
Well thanks, looking forward.

**Comment by vpirogov** [comment]
Commit 86dde8750b18cea271dab00303dd607898d54194 introduces optimized SGEMM to the library and removes binary dependency from inner product. 

There's no way to go away from OpenMP as long as you want the code to be threaded. @tensor-tang, could you please elaborate on what threading model you are using in your application?

**Comment by tensor-tang** [comment]
Thanks @vpirogov.
I was trying to integrate mkl-dnn directly into other framework. So in this point of view, the prefer way is that I do not need to add or handle omp and cblas in my project, mkldnn would handle them independent.

However I have already added them, and seems have some competes BTW mkldnn and my thread. But is not first priority now, so I was hoping mkldnn could handle them.

**Comment by vpirogov** [comment]
The library does not require you to manage OpenMP explicitly. By default it will try to use all the cores available in the system for the best possible performance. The only scenario when you need to be aware of OpenMP threading is when you are calling the library from multiple threads in your application. When you get to the point when you will be looking into this let us know and will be able to help.

**Comment by tensor-tang** [comment]
OK, thanks @vpirogov
