### ISSUE TITLE
Issue when "make install" 

### ISSUE THREAD

**Issue by curlyt** [01org/mkl-dnn#21]
hi ,

I followed the steps to install MKLDNN. However, in the last step when I want to "make install". It showed the Error msg as below. 

Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libmklml_intel.so
CMake Error at cmake_install.cmake:36 (FILE):
  file INSTALL cannot copy file
  "/home/curly/mkl-dnn/external/mklml_lnx_2017.0.1.20161005/lib/libmklml_intel.so"
  to "/usr/local/lib/libmklml_intel.so".

can anyone helps me?

**Comment by rsdubtso** [comment]
Did you specify CMAKE_INSTALL_PREFIX? If not then the default install prefix /usr/local which is usually writable only by the root user. Please point CMAKE_INSTALL_PREFIX to a directory writable by your user. For example
`cmake -DCMAKE_INSTALL_PREFIX=$HOME/mkldnn`.

**Comment by curlyt** [comment]
It works, thank you!
