### ISSUE TITLE
so many error when compiling on windows with visual studio

### ISSUE THREAD

**Issue by anguoyang** [01org/mkl-dnn#24]
hello, I have compiled the source code on windows/visual studio after configured with cmake, there are so many errors, such as(there are more than 500 errors): 

Severity	Code	Description	Project	File	Line	Suppression State
Error		the global scope has no "posix_memalign"	mkldnn	
Severity	Code	Description	Project	File	Line	Suppression State
Error		identifier "jit_conv_call_s" is undefined	mkldnn	
    void operator()(jit_bnrm_call_s *arg) { jit_ker(arg); }
Severity	Code	Description	Project	File	Line	Suppression State
Error		more than one conversion function from "lambda [](mkldnn::memory::primitive_desc)->mkldnn::c_api::mkldnn_primitive_desc_t" to "<error-type>" applies:	simple-net-cpp	C:\myproject\intel\caffe\external\mkldnn\include\mkldnn.hpp	594	
............................................................

anyone compiled the source code successfully on windows? thanks.

I have installed the intel xe 2017(with c++ compiler) evaluation, and tried to compile it with intel c++, but still failed.

**Comment by rsdubtso** [comment]
Windows is not yet supported. See issue #10 for additional discussion.
