### ISSUE TITLE
Benchmark results?

### ISSUE THREAD

**Issue by szha** [01org/mkl-dnn#25]
Hi,

Thanks for putting together this library. Is there any benchmark results for the performance of this library that can be shared? Thank you.

-sz

**Comment by vpirogov** [comment]
I don't have anything I can share at the moment. Is there a particular system you care about? You can measure performance on your system though using [Intel's fork of Caffe](https://github.com/intel/caffe) or [DeepBench](https://github.com/baidu-research/DeepBench).
