### ISSUE TITLE
performance drop with GooglenetV1

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#26]
Before v0.5 I used padR=padding in pooling layer, it works well and got a very good perf with googlenet scoring.
However with this new release, there is a check point in Pooling.cpp:
```    
 for (int i = 2; i <= 3; ++i)
        consistency = consistency && (
                (src_desc->dims[i] - kernel[i - 2] + padding_l[i - 2]
                 + padding_r[i - 2]) / strides[i - 2] + 1
                == dst_desc->dims[i]);
    if (!consistency) return invalid_arguments;
```
So I have to use padR just like the test case:
```
for (int i = 0; i < 2; ++i) {
        if ((pd.ih + pd.padh + padR[0] - pd.kh)/pd.strh + 1 < pd.oh) ++padR[0];
        if ((pd.iw + pd.padw + padR[1] - pd.kw)/pd.strw + 1 < pd.ow) ++padR[1];
 }
```
Then the fps drops to **HALF** before.
And there are about 4 pooling cases in GooglenetV1 this padR would be used, taking much more time than before.

I thought the output memory would be clear to zero, before pooling right? So even if I use padding(instead of padR), the loss result was still right with much better performance.

PS: padding_kind::zero

So any possible improvement ?

**Comment by vpirogov** [comment]
Thanks for catching this. We changed the way we handled padding in pooling to be consistent with TensorFlow and MXNet frameworks, but this resulted in code falling back to reference pooling implementation in case of uneven padding. We will address the issue and performance for this case will be on par with what you observed before.

**Comment by tensor-tang** [comment]
Thanks, looking forward.

**Comment by vpirogov** [comment]
378dcf97e28be7301e9ca2d3448a2a272de2820e fixes this issue.
