### ISSUE TITLE
make test stalled

### ISSUE THREAD

**Issue by uu-praveeng** [01org/mkl-dnn#28]
Hi,
I built the mkl-dnn but make test wont run. 
Running tests...
Test project /home/gaurav/GPraveen/mkl-dnn/build
      Start  1: simple-net-c
It is halting with the above error.

Intel processor that my PC has in Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz with out avx2.
Is this the issue will it work only for intel Xeon processors that they have mentioned?

Thanks in advance

**Comment by vpirogov** [comment]
Thanks for your report. This library is not yet optimized for processors without Intel(R) AVX2 support. It will run reference implementation that is rather slow and tests might take long time to complete. This might be what you are experiencing.

I also do not see specific error message in the log you provide. Is this all the output you get?

**Comment by uu-praveeng** [comment]
There are no error messages as such. But it is taking long enough time. Dint wait that much long to see the output to come up. 
I thought there could be some thing that I was missing hence I posted.
How much time will it take to run the test if the processor in non Intel Xeon?

**Comment by rsdubtso** [comment]
mkl-dnn is only optimized for AVX2 and (partially) AVX512. This means that it should work on any mobile/desktop/server CPU that supports those instruction sets, so it does not require a Xeon CPU.

For older CPUs that do not support at least AVX2, mkl-dnn falls back to reference implementations that are *very* slow. We also seem to have a bug where we do not correctly check for supported ISA and try executing AVX2 code on CPUs that do not support it.

**Comment by liyancas** [comment]
@rsdubtso  Does mkl-dnn will be optimized for CPU with AVX in the future? I tested the inference results with mkl-dnn on AVX CPU, but it's much too slower than im2col + MKL GEMM method.

**Comment by rsdubtso** [comment]
There are no such plans at the moment. Of course we will consider pull requests that add such optimizations.
