### ISSUE TITLE
Convolution Performance versus MKL 2017

### ISSUE THREAD

**Issue by sbodenstein** [01org/mkl-dnn#29]
What is the performance of mkl-dnn convolution versus the MKL 2017 implementation (say for a 3x3 convolution)? 

I saw that the [Update 2 of MKL 2017 got](https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2017-release-notes) "Significantly improved reference convolution code performance". Does this library also benefit from these improvements? Or does one pay a performance penalty using this library?

**Comment by rsdubtso** [comment]
Performance of mkl-dnn is not yet on par with MKL, For 3x3 forward/inference I expect the performance to be within 5-10% of AVX2. Other cases may be hit and miss: some cases that are optimized in MKL would fall back to reference implementation in mkl-dnn.

You can use https://github.com/baidu-research/DeepBench to compare the two libraries on your hardware on convolution cases you are interested in.
