### ISSUE TITLE
What are the advantages of using a JIT for several operators ? 

### ISSUE THREAD

**Issue by blackball** [01org/mkl-dnn#3]
Hi, 

MKL-DNN is using xbyak to generate the codes for some of the operators (conv, pooling, etc) in every forward pass. I wonder what are the advantages here by doing this. 

To get optimal performance by hand coding the implementation in asm ? How much is the gain compare to implementing it by using C++ and SIMD instructions ?  Why does it generate the codes in every run ? 

Thanks!

**Comment by vpirogov** [comment]
In MKL-DNN we use XByak to implement low level kernels directly in assembly. The same results can be achieved implementing these kernels using C++ intrinsics, however JIT code generation has two advantages. The first is portability. XByak does not require assembler to generate code, does not rely on compiler intrinsics or inline assembly syntax, and generates the same machine code with any compiler. The second is that we can generate low level kernels for specific problem shape and size, resulting in better performance. For instance in convolutions with padding we do not process zeroes reducing the number of operations necessary to compute the convolution. With inline assembly this requires writing multiple variants of the same kernel to cover possible corner cases.

Code generation happens at topology initialization stage. Once primitive is created you can execute it multiple times on different data buffers without code generation.

Hope this helps.

Regards,
Vadim

**Comment by naibaf7** [comment]
@bhack 
Yup, LibDNN uses these advantages as well, but for GPUs.

**Comment by blackball** [comment]
@vpirogov Thanks for your reply. I checked the source codes again, yes, the codes was generated in the kernel construction time. 

Since mkl-dnn is using Xbyak, the portability is very limited. 

Do you have any benchmark comparing mkl-dnn with caffe, mxnet ? How much faster is it ? 

Thanks!

**Comment by alheinecke** [comment]
At Intel Labs we have a research project, called LIBXSMM (https://github.com/hfp/libxsmm), which also relies on runtime code generation at a higher level than Xbyak. LIBXSMM is used in Baidu's DeepBench suite (https://github.com/baidu-research/DeepBench, https://software.intel.com/en-us/articles/intel-xeon-phi-delivers-competitive-performance-for-deep-learning-and-getting-better-fast) for non-square convolutions (but could be used for squared as well). Under samples/dnn we have a couple of scripts for benchmarking layer performance.

**Comment by blackball** [comment]
@alheinecke I have star-ed libxsmm for long time, didn't know that it also has these dnn kernels implemented. I will give it a check. Thanks very much!

**Comment by vpirogov** [comment]
@blackball Could you please elaborate on the statement that using XByak limits portability?

MKL-DNN is not a framework, it's a framework acceleration library. So you can't make comparison of MKL-DNN vs Caffe or MXNet. Currently MKL-DNN is integrated into [Intel's fork of Caffe](https://github.com/intel/caffe) and provides significant acceleration to CPU code path in comparison with BVLC Caffe.

**Comment by bhack** [comment]
@vpirogov Some of the Intel contributed GPU kernels are merged in the @naibaf7 official Caffe Opencl branch. Will mkl-dnn add GPU device type in engine?

**Comment by blackball** [comment]
@vpirogov for instance, XByak lacks support for ARM platform which is widely used in consumer devices. 

The reason why I asked for comparison with other libs is mkl-dnn has the full functionality to construct a full convolutional network as it shows in examples/simple_net.cpp.

**Comment by vpirogov** [comment]
@blackball Thanks for clarification. XByak-optimized kernels are dispatched only for supported architectures. The rest will run reference implementation and it's possible to implement ARM-specific code path. In any case low level optimizations will not be portable between incompatible architectures.

**Comment by vpirogov** [comment]
@bhack Adding support for Intel HD Graphics via OpenCL is one of the directions we are investigating.

**Comment by bhack** [comment]
@vpirogov @blackball There was an old ARM rip-off Xbyak at https://github.com/wanabe/xtaak

**Comment by blackball** [comment]
@bhack Thanks!
