### ISSUE TITLE
pure zero output of softmax

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#30]
I got "Inf" cost in my training phase.
Finally found that there have many pure 0 as the output of softmax.
This has no impact on scoring, but when in training phase this could be an issue with std::log(0).

Is this normal? Or should I add EPS myself manually?
I thought this could be done in MKL-DNN, enhancing the robustness.

Thanks~

**Comment by DmitryRizshkovg** [comment]
Hi!

Softmax is using exp function and if your input values > 710 or < -710 exp will return INF.

Softmax primitive first trying to rescale inputs by looking for max value and next subtracting max value from inputs. But this might not work if input range is too large, let say from -15000 to 5000. 

To fix this input could be normalized with mean value or by rescaling values to range from 0 to 1 (like for LeNet).

Dmitry

**Comment by tensor-tang** [comment]
However my input value would not out range, which has already been normalized.
Here my point is trying to say that the output of softmax do not have EPS, since I just got pure zero. 
And this could cause Inf in next cost layer with log(0).

**Comment by DmitryRizshkovg** [comment]
Yes, Softmax primitive do not have EPS

**Comment by tensor-tang** [comment]
Thanks @DmitryRizshkovg 
So would it be added to avoid Inf?

**Comment by rsdubtso** [comment]
There seem to be no plans to do that now. Closing. Please reopen if this is a high priority.

**Comment by luotao1** [comment]
@rsdubtso @DmitryRizshkovg
Do you have a plan to avoid the output of softmax to be 0?
If adding EPS manually, I'm afraid that the training speed will be slow down.
