### ISSUE TITLE
no any AVX code found for FC backward

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#31]
No any avx implement for inner product backward?
Only saw ref code, which is extremely slow.

**Comment by vpirogov** [comment]
Current implementation does not include optimized backward propagation in inner product for any instruction sets. We will add this support shortly.

**Comment by tensor-tang** [comment]
Thanks @vpirogov 
Looking forward.

**Comment by vpirogov** [comment]
Fixed with d181eb180b3e261428eff586b536c60f5b983a68

**Comment by tensor-tang** [comment]
That's great.
I will try, Thanks
