### ISSUE TITLE
AVX2 functions not called ... clarification needed

### ISSUE THREAD

**Issue by uu-praveeng** [01org/mkl-dnn#35]
Hello 

We are using latest intel mkl-dnn from the git hub. We are compiling and testing performance on a Ubuntu 14.04LTE PC which has AVX2 support.  However, it appears that the AVX2 functions are not being invoked (appears that it is invoking _ref_convolution_fwd_t in ref_convolution.cpp instead of  _jit_avx2_convolution_fwd_t in jit_avx2_convolution.cpp). Memory format used is NCHW.

However, it appears that the AVX2 functions are being used if Memory format for Weights/Inputs/Outputs is changed to other formats such as OIhw8i8o etc.

As we cannot rearrange the order of inputs/weights run-time, how to ensure that AVX2 functions will be called irrespective for memory format without impacting the accuracy. 

Thanks in advance 
Praveen

**Comment by shelleygoel** [comment]
Hi Praveen,

I would suggest setting up convolution with input/output format `any` and creating reorders. This will allow convolution to chose the memory best suited for performance on AVX2(or any other CPU). Please look at [examples](https://github.com/01org/mkl-dnn/tree/master/examples) (simple_training_net.c or simple_training_net.cpp) for creating reorders. 

Hope this helps,
Shelley

**Comment by uu-praveeng** [comment]
Thanks for quick reply . 
Changed accordingly and is working.
