### ISSUE TITLE
simplenet.cpp has incorrect pooling layer

### ISSUE THREAD

**Issue by akeygma** [01org/mkl-dnn#36]
In call to pooling_forward, pool_indices_memory should appear as 4th parameter.

    net.push_back(pooling_forward(pool_pd, lrn_dst_memory, pool_indices_memory, 
        pool_dst_memory));

**Comment by igorsafo** [comment]
You are right. We will fix it.
Thank you!

**Comment by igorsafo** [comment]
[ccf914f](https://github.com/01org/mkl-dnn/commit/ccf914f5fc1e3122f03cd28d379c13a3114f323c) fixes this issue.
