### ISSUE TITLE
fully connected layer optimal code

### ISSUE THREAD

**Issue by uu-praveeng** [01org/mkl-dnn#37]
Hi,

For fully connected Layer I have used the sgemm, cblas_sgemm and I got some reasonable number x ms.
When I tried to use the innerproduct available for fullyconnected from mkldnn I am getting more then x ms.

Please suggest if I am missing anything here . Ideally the innerproduct which internally calls avx2 gemm should be less than xms?

Thanks,
Praveen.

**Comment by vpirogov** [comment]
Hi Praveen,

Intel MKL-DNN can use two different implementation of SGEMM: JIT based version included in the library or Intel MKL implementation from [binary dependency](https://github.com/01org/mkl-dnn/releases/download/v0.7/mklml_lnx_2017.0.2.20170209.tgz). If you are linking with Intel MKL implementation performance of inner product should be on par with what you do. JIT based version might be slower for some shapes and size.
