### ISSUE TITLE
any format works for all layers now?

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#39]
As I know, for conv layer, no matter forward and backward, I can get the best format if use any, right?

How about other layers, like pool?

As pooling layer:

Suppose that we have a simple net: CONV1->POOL1->CONV2.

For forward: if the output format of CONV1 is nchw, then the POOL1 will directly use nchw as input foramt, since pool layer seems do not handle src format as any(maybe we can add it ??).

Likewise for backward: the CONV2 may have nchw as botdiff format, so POOL1 will directly use it.

We do not want to see these cases right? Users may hope nChw8c/nChw16c can be used as the input format if appropriate. 

That's for pool layer, how about other layers, like batch norm, fc and concat?

Thanks very much.

**Comment by vpirogov** [comment]
Format any is designed to allow compute intensive layers like convolution and inner product to choose the layout which will result in the best performance. The rest of the layers, including relu, lrn, batch norm and concats/splits will work with all the layouts that come out of the convolutions or inner products. When creating these primitives you should use previous layer output descriptor directly. Please refer to examples or [documentation](http://01org.github.io/mkl-dnn/).
