### ISSUE TITLE
make test failed.

### ISSUE THREAD

**Issue by caspell** [01org/mkl-dnn#40]
Hi. 

i use 'Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz'

The following tests FAILED:
          1 - simple-net-c (OTHER_FAULT)
          2 - simple-net-cpp (OTHER_FAULT)
          3 - simple-training-net-c (SEGFAULT)
Errors while running CTest

another passed

[ this is logs]
Running tests...
Test project /home/framework/mkl-dnn/build
      Start  1: simple-net-c
*** Error in `/home/framework/mkl-dnn/build/examples/simple-net-c': free(): invalid pointer: 0x00007faaee350010 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7fab3b6a6503]
/home/framework/mkl-dnn/build/examples/simple-net-c(+0x23cc)[0x7fab42f423cc]
/home/framework/mkl-dnn/build/examples/simple-net-c(+0x11ca)[0x7fab42f411ca]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fab3b64bb35]
/home/framework/mkl-dnn/build/examples/simple-net-c(+0x1239)[0x7fab42f41239]
======= Memory map: ========
7faab66ca000-7faab66cb000 ---p 00000000 00:00 0
...
...
 1/24 Test  #1: simple-net-c ..........................***Exception: Other  6.10 sec
      Start  2: simple-net-cpp
*** Error in `/home/framework/mkl-dnn/build/examples/simple-net-cpp': free(): invalid pointer: 0x00007f784172e040 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f7884b6c503]
/home/framework/mkl-dnn/build/examples/simple-net-cpp(+0x70b9)[0x7f788cc2e0b9]
/home/framework/mkl-dnn/build/examples/simple-net-cpp(+0x4c76)[0x7f788cc2bc76]
/home/framework/mkl-dnn/build/examples/simple-net-cpp(+0x2a1d)[0x7f788cc29a1d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f7884b11b35]
/home/framework/mkl-dnn/build/examples/simple-net-cpp(+0x2b3c)[0x7f788cc29b3c]
======= Memory map: ========
7f7809aa8000-7f7809aa9000 ---p 00000000 00:00 0
...
...
 2/24 Test  #2: simple-net-cpp ........................***Exception: Other  7.88 sec
      Start  3: simple-training-net-c
 3/24 Test  #3: simple-training-net-c .................***Exception: SegFault 32.32 sec
      Start  4: simple-training-net-cpp
 4/24 Test  #4: simple-training-net-cpp ...............   Passed   13.11 sec
      Start  5: api-c
...

$lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core

$gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thank you.

**Comment by shelleygoel** [comment]
Hi Caspell,

Thanks for pointing this out. We are looking into it and will fix it soon.

Best,
Shelley

**Comment by caspell** [comment]
Thanks, it is working.
