### ISSUE TITLE
Program hung on MKL-DNN

### ISSUE THREAD

**Issue by etaf** [01org/mkl-dnn#41]
Hi, I run my program on KNL and find it hung at  src/cpu/jit_gemm_convolution_utils.cpp: line 158: 
```cpp
        for (size_t i = 0; i < jcp.im2col_size; ++i) (*ws)[i] = 0.;
```
Seems it use avx512 to do this.
In my terms, I just want to pass this hung point,
Will there be any issue of MKL-DNN if I comment this line since it just initialize the memory as 0 ?

**Comment by igorsafo** [comment]
Hi!
Could you please provide more details regarding sizes of your convolution?
This line of code just fills the memory by 0 and you can get incorrect results if you comment it.

Regards,
Igor

**Comment by rsdubtso** [comment]
Closing since there's not much progress. Please feel free to reopen.
