### ISSUE TITLE
convolution bwd data is very slow in jit_gemm_convolution path

### ISSUE THREAD

**Issue by jzhoulon** [01org/mkl-dnn#42]
Hi, our workload is unbalance on jit_gemm_convolution_bwd_data path, we have a 2*3*2240*2240 input need to be run on googlenet, batch size =2 , input channel =3. We find that the first conv layer's backward data goes into jit_gemm_convolution path, and it will fork two thread to do the sgemm and col2img(workamount = ngroup*nbatchsize), per thread has to deal with 3*2240*2240 input. How ever, our cpu is Xeon phi knl, it has 68 cores, other 66 cores are idel during this time.So it is very efficient. How can we solve it? or is it possible to make it run through jit_avx512/jit_avx2 path? format has been set any now, Thanks

**Comment by jzhoulon** [comment]
is there some workaround that we can make it run on avx2 / avx512 path. the only insufficient condition is our stride is 2., pad is 3, channel is 3

**Comment by vpirogov** [comment]
Current implementation does not have jit codepath for backward convolution by data in case of 3 channels.  So your case runs GEMM-based convolution which is threaded by minibatch currently and with minibatch 2 only 2 threads are used. To get better balancing you can increase minibatch and make it a multiple of number of cores.

In general convolution with 3 channels is used as the first layer in the topology and there's no need to compute gradient. In case of GoogleNet in particular backward by data for the first convolution is not computed. Is there a particular reason why you want to compute backward by data in this scenario?

**Comment by jzhoulon** [comment]
Thanks for the quick response! Our framwork's graph is dynamic so its hard to know who is first layer. We will try to optimize it to make the first layer be recognized. Thanks
