### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by jiyuanz** [01org/mkl-dnn#43]
Hi, 
I am new to the Xeon Phi co-processor. I was trying to install the library on a KNL machine, however, I got the following error at the "make" stage:

[ 32%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_lrn.cpp.o
[ 34%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_inner_product.cpp.o
/mkl-dnn/src/cpu/gemm_inner_product.cpp:39:24: error: variable or field
‘cblas_gemm’ declared void
 inline void cblas_gemm(CBLAS_LAYOUT layout,
                        ^
/mkl-dnn/src/cpu/gemm_inner_product.cpp:39:24: error: ‘CBLAS_LAYOUT’
was not declared in this scope
....

The compiler and mkl environment was set already.  Could you help me with this error? Thanks!

Best regards,

**Comment by rsdubtso** [comment]
Can you please show cmake output?

**Comment by jiyuanz** [comment]
Hi,
Thanks for the reply. This is cmake output:

 The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Intel(R) MKL found: include /opt/intel/composer_xe_2013_sp1.1.106/mkl/include, lib /opt/intel/composer_xe_2013_sp1.1.106/mkl/lib/intel64/libmkl_rt.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: **/mkl-dnn/build

**Comment by rsdubtso** [comment]
You seem to be using a very old MKL. Can you please try a more recent one which you can [get for free](https://registrationcenter.intel.com/en/forms/?productid=2558&licensetype=2)?  Another option is to download a stripped down library referenced in the [Release Notes for v0.7](https://github.com/01org/mkl-dnn/releases/tag/v0.7).

**Comment by rsdubtso** [comment]
Assuming this is resolved. Feel free to re-open if it is not.
