### ISSUE TITLE
segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by caspell** [01org/mkl-dnn#50]
HI,
I successfully completed 'make test' and 'make install' after fixed error [(https://github.com/01org/mkl-dnn/issues/40).](url)
but , when i run intel/caffe train model  by '--engine=MKLDNN' then occur segmentation fault error and stopped train.
If i run by '--engine=MKL2017' then no error.

[error logs]
...
I0418 09:31:32.606019 104068 net.cpp:365] data does not need backward computation.
I0418 09:31:32.606083 104068 net.cpp:407] This network produces output loss
*** Aborted at 1492475492 (unix time) try "date -d @1492475492" if you are using GNU date ***
PC: @     0x7f5b98ff4360 MLSL::Free()
*** SIGSEGV (@0x0) received by PID 104068 (TID 0x7f5b9c6e6a80) from PID 0; stack trace: ***
    @     0x7f5b9b1b5370 (unknown)
    @     0x7f5b98ff4360 MLSL::Free()
    @     0x7f5b9c161ceb caffe::Net<>::Init()
    @     0x7f5b9c162dae caffe::Net<>::Net()
    @     0x7f5b9c1314f2 caffe::Solver<>::InitTrainNet()
    @     0x7f5b9c131acc caffe::Solver<>::Init()
    @     0x7f5b9c131e38 caffe::Solver<>::Solver()
    @     0x7f5b9c0a92c3 caffe::Creator_SGDSolver<>()
    @     0x7f5b9c75c787 caffe::SolverRegistry<>::CreateSolver()
    @     0x7f5b9c753b5b train()
    @     0x7f5b9c74d9dc main
    @     0x7f5b90597b35 __libc_start_main
    @     0x7f5b9c74e81d (unknown)
segmentation fault (core dumped)

**Comment by emfomenk** [comment]
Hi @caspell,

Most likely the problem is in MKL-DNN integration to IntelCaffe.
I think it is better to file an issue there: [IntelCaffe bug-tracker](https://github.com/intel/caffe/issues).

(sorry for delay with response)
