### ISSUE TITLE
AVX support patch

### ISSUE THREAD

**Issue by Evgueni-Petrov-aka-espetrov** [01org/mkl-dnn#51]
Dear MKL DNN developers,

Would you be interested in reviewing a patch which adds AVX support to convolution forward scoring?
With this patch on AVX machines, we see about 70-80% CPU utilization in single thread with 1x1 convolutions, and about 90% with regular convolutions.

Thank you,
Evgueni.

**Comment by rsdubtso** [comment]
Hi Evgueni. Yes, we would. Please submit a PR.

**Comment by HAIDJ** [comment]
Dear Evgueni-Petrov,

I am very interested in your AVX patch.
Could I please review the source code.
@Evgueni-Petrov-aka-espetrov 

Thank you,
Daejin Jung

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi Daejin,
I hope to submit a PR by the end of this week.
E.

**Comment by HAIDJ** [comment]
Dear Evgueni-Petrov,

Thank you and I look forward to hearing from you.

Daejin Jung.

**Comment by rsdubtso** [comment]
It's been a while... closing as old. Please reopen or just post a PR.
