### ISSUE TITLE
stuck at test 21 

### ISSUE THREAD

**Issue by darrenscrews** [01org/mkl-dnn#57]
during "make test" it never proceeds past start 21: test_convolution_forward, it just hangs there.  This is happening both on a 6th gen core processor and Atom processor.

**Comment by vpirogov** [comment]
Thanks for your report. Tests 21-24 have extensive coverage of various convolution flavors and take about 10 minutes each on server system. For Atom this might be longer as this includes backward convolutions that run SGEMM or reference code path on this system. How much time the tests were working?

**Comment by darrenscrews** [comment]
my core CPU finally finished test 21 after about 40 minutes, I'll probably have to let my Atom CPU run overnight.  I'll update after it finishes.

**Comment by vpirogov** [comment]
Thanks for the update. We'll look at reducing amount of tests to make the runs more manageable on client platforms.

**Comment by vpirogov** [comment]
As you are trying to run MKL-DNN on Atom you might want to pull the latest refs (ecf1883a94239a19d442356d32e1076a15b88e7a). These include more primitives optimized for sse4.2.
