### ISSUE TITLE
convolution struct members

### ISSUE THREAD

**Issue by steenax86** [01org/mkl-dnn#6]
Hello,

This is a question to verify my interpretation of  ` test_convolution_descr_t` members in `mkldnn_test_common.hpp`

```
 mb; // Size of mini-batch
 ng; // What does ng stand for?
 ic, ih, iw; //Input: number of channels, height, and width
 oc, oh, ow; //Output: number of channels, height, and width
 kh, kw; // filter: height and width
 padh, padw; //padding dimensions
 strh, strw; // stride: height and width
```

Thanks,
Steena

**Comment by vpirogov** [comment]
Hi Steena,

You interpretation is correct. `ng` describes the number of groups in convolution as described in [AlexNet paper](http://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf).
