### ISSUE TITLE
debug compile

### ISSUE THREAD

**Issue by kruus** [01org/mkl-dnn#62]
1-liner change suggestion:

For debug mode examples/simple-net-c to pass (for example),
things like pooling.cpp ask for the accumulator type given arguments f32, undef, f32. 
So perhaps consider changing the type_helpers.hpp:112 default_accum_data_type
line from 'everyone_is(f32,...)' to something like:

if (everyone_is(f32, src_dt, dst_dt) && one_of(wei_dt, f32, data_type::undef)) return f32;

to avoid triggering the "unimplemented use case" assertion.
Even though the default return value is actually correct, I think it's good to keep the assertion.

**Comment by emfomenk** [comment]
Hi @kruus,

Yeah, thanks for catching that!
Fixed (in slightly another way) with the following [commit](https://github.com/01org/mkl-dnn/commit/fcd35d60897b8a524d344c8b1699e362256f808f).
