### ISSUE TITLE
Does MKL-DNN support caffemodel and prototxt file ?

### ISSUE THREAD

**Issue by ligongzheng** [01org/mkl-dnn#68]
In the introduction of MKL-DNN, it's said the MKL-DNN is intended for accelerating deep learning frameworks on IA. But I feel like it's isolated with other deep learning frameworks liking a new framework.
I use it by the way writing in the examples. And I wonder if there something wrong for me  to use the MKL-DNN ? Or if I use it rightly,How can I read the prototxt and caffemodel file from caffe framework in MKL-DNN code ?

**Comment by rsdubtso** [comment]
MKL-DNN itself is not a DL framework. Instead, it provides a set of computational primitives to be used by DL frameworks.

IntelCaffe (https://github.com/intel/caffe) supports MKL-DNN out of the box, but there're still some rough edges. Support in other frameworks is in the pipeline.

**Comment by ligongzheng** [comment]
Thank you a lot, I will try intelCaffe.
