### ISSUE TITLE
What kind of  blas does intelCaffe use (default)?

### ISSUE THREAD

**Issue by ligongzheng** [01org/mkl-dnn#74]
In the Makefile.config,the intelCaffe set the blas := mkl but leave commented for BLAS_INCLUDES and BLAS_LIB. When I use "ldd ./caffe" commend ,I  did not find the mkl blas library. In  my thought,if we chose to use mkl for blas, we should both change the "blas := mkl" and set the BLAS_INCLUDES,BLAS_LIB in the same time. So I wonder if we finally use the mkl for blas or not ?

**Comment by rsdubtso** [comment]
Can you please show full ldd output? IntelCaffe links to `libmkl_rt.so` (in case you have full MKL) or `libmklml_intel.so` (in case you use a stripped-down MKLML version aimed at ML workloads). Both libraries provide BLAS implementation. In my Makefile.config I have only `BLAS := mkl` and let IntelCaffe build system figure out what to link to and where find the MKL include files based on the `MKLROOT` environment variable. If it is empty, IntelCaffe would download MKLML for you, unpack it, and use it.

**Comment by ligongzheng** [comment]
OK.Actually I thought the libmklml_intel.so is something about machine learning that it was isolated with blas function.  Thank for your explanation.
