### ISSUE TITLE
different performance between ubuntu 14.04 and ubuntu 16.04 

### ISSUE THREAD

**Issue by ligongzheng** [01org/mkl-dnn#76]
hello:
       I  run a simple test on different version of ubuntu(14.04 and 16.04).This is my code:
https://gist.github.com/ligongzheng/d4764b0497f452b8c0317c06825bdafc

I compile the code with the command line:g++ -std=c++ ./simple_net_li.cpp -o ./simple_net_li -lmkldnn `pkg-config --cflags --libs opencv`   
Finally,the time is different between on ubuntu 14.04 and 16.04.On ubuntu 16.04,it cost 2.6ms but on ubuntu 14.04,it cost 2.2ms. 
It's normal ? Could anyone explain this for me ? Thank you advanced.

**Comment by ligongzheng** [comment]
The code is very similar to the example(simple_net.cpp),I just add a function of reading a picture and countting the time.

**Comment by rsdubtso** [comment]
Can you please post this as a gist?

**Comment by ligongzheng** [comment]
OK,I have posted it as a gist.Thank you for your concern.

**Comment by rsdubtso** [comment]
Which part of the code costs differently between the OSes? The difference seems quite small to me esp. taking into account the fact that absolute times are also very small. How reproducible is the difference? Does the difference persist if you do not take into account the I/O bound parts and the time it takes to perform memory allocation?

**Comment by ligongzheng** [comment]
SELinux-friendly ? I set the OS in non-security model when I installed the ubuntu 16.04 for additional NVIDIA driver . is that the reason ?

**Comment by rsdubtso** [comment]
If SELinux is disabled or in non-enforcing mode, then Xbyak should run just fine.

**Comment by emfomenk** [comment]
I would suggest looking into more accurate perf benchmark rather than into simple_net_c (the only purpose of that one was to illustrate the API usage).
Namely:
* [DeepBench](https://github.com/baidu-research/DeepBench/tree/master/code/intel/convolution/mkl_conv)
* [**benchdnn**](https://github.com/01org/mkl-dnn/tree/master/tests/benchdnn)

**Comment by rsdubtso** [comment]
No response for over a week. Closing. Please feel free to reopen.
