### ISSUE TITLE
softmax patch with openmp and mkl

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#79]
hi,

I found that ref_softmax did not use openmp or mkl to sppedup.
It takes much time when batchsizes and channels are very large, so I use mkl and openmp to speedup the "execute_forward_dense" function.

And I have run some tests to compare the before and after performance:
It shows about x10 ~ x90 improvement on SKX.
![image](https://user-images.githubusercontent.com/21351065/27389252-6e50ffb8-56d0-11e7-9948-98f6fc4a878b.png)
format: nc
batchsize: 128
channel: 100~20000

So I submit a [PR ](https://github.com/01org/mkl-dnn/pull/78) here.

Hope it would be useful.

Thank you,

**Comment by emfomenk** [comment]
Hi @tensor-tang,

We will review that and promote soon.
Great thanks for the PR!

**Comment by tensor-tang** [comment]
Thank you @emfomenk and I am looking forward.
