### ISSUE TITLE
Mkldnn debug version crashes.

### ISSUE THREAD

**Issue by nbpatel** [01org/mkl-dnn#80]
I am on commit 
commit 96b1ea215b6a2ec86c8b51d9216c458a3b34229a
Author: Andrey Kalinin <andrey.kalinin@intel.com>
Date:   Sun Jun 11 13:29:10 2017 -0700

Ran the tests as well in debug mode. 
[ RUN      ] Forward_GoogleNetV2_Blocked16_part2/convolution_test.TestConvolution/34
test_convolution_forward_f32: /nfs/site/home/nbpatel/mkl-dnn/src/cpu/jit_avx512_common_1x1_conv_kernel_f32.cpp:888: static mkldnn::impl::status_t mkldnn::impl::cpu::jit_avx512_common_1x1_conv_kernel_f32::init_conf(mkldnn::impl::cpu::jit_1x1_conv_conf_t&, const convolution_desc_t&, const mkldnn::impl::memory_desc_wrapper&, const mkldnn::impl::memory_desc_wrapper&, const mkldnn::impl::memory_desc_wrapper&, bool, double, int, bool): Assertion `jcp.load_dim % load_blocking == 0' failed.
Aborted (core dumped)

**Comment by ankalinin** [comment]
Hi Nishant , 

Thanks for reporting the issue. It's fixed by 25ee9f5. There was not correct condition in assertion.

**Comment by emfomenk** [comment]
Closed with [25ee9f5](https://github.com/01org/mkl-dnn/commit/25ee9f5af93e103098146f05f7b15be67de3b67c)
