### ISSUE TITLE
convert from boost::shared_prt to std::shared_ptr

### ISSUE THREAD

**Issue by ligongzheng** [01org/mkl-dnn#86]
Hi:
   I implement the mkldnn in my own net as a engine and I rebuid the mkldnn_memory.cpp without template. But I have the problem like below:
/home/lgz/mini-caffe/include/caffe/mkldnn_memory.hpp: In member function ‘std::shared_ptr<caffe::MKLDNNMemoryDescriptorBase> caffe::MKLDNNMemoryDescriptorBase::get_shared_ptr()’:
/home/lgz/mini-caffe/include/caffe/mkldnn_memory.hpp:95:38: error: could not convert ‘boost::enable_shared_from_this<T>::shared_from_this() [with T = caffe::MKLDNNMemoryDescriptorBase]()’ from ‘boost::shared_ptr<caffe::MKLDNNMemoryDescriptorBase>’ to ‘std::shared_ptr<caffe::MKLDNNMemoryDescriptorBase>’
         return this->shared_from_this();

How solve this problem ? Thank you in advanced !

**Comment by rsdubtso** [comment]
There's not enough context to answer this. Also, I don't think this has anything to do with mkl-dnn and is best answered by mini-caffe developers. For what its worth, there's a stackoverflow question on this topic: https://stackoverflow.com/questions/6326757/conversion-from-boostshared-ptr-to-stdshared-ptr. Closing as offtopic.
