### ISSUE TITLE
Ambiguous Dependencies

### ISSUE THREAD

**Issue by gangliao** [01org/mkl-dnn#91]
You didn't  include `libmkl_rt.so` in mklml_lnx_2018.0.20170425.tgz
  
Why you expect to find detect_mkl("libmkl_rt.so")?

**Comment by rsdubtso** [comment]
To allow linking with full MKL.

**Comment by gangliao** [comment]
Is that means even use `mklml_lnx_2018.0.20170425.tgz`,we still need to install full MKL

**Comment by rsdubtso** [comment]
You should be able to use either. Did you run into any issues?

**Comment by gangliao** [comment]
I have trouble on Mac OS X, is there a roadmap to support Mac OS X? I know it's not easy since only GCC has built in `openmp`.

**Comment by vpirogov** [comment]
We are working on enabling macOS support, stay tuned. You might want to look at #84. Also keep in mind that you'll need macOS version of libmklml which is available [here](https://github.com/01org/mkl-dnn/releases/download/v0.9/mklml_mac_2018.0.20170425.tgz)

**Comment by rsdubtso** [comment]
I don't think I've ever tested that patch for OSX support with MKLML. I'll try to find some time to do that over the weekend.

**Comment by gangliao** [comment]
@rsdubtso yeah, just I mentioned,  many places need be revised in CMake to support Mac OSX.
For instance, the detect name `detect_mkl("libmkl_rt.so")`, you guys use the different name for same library under different operating systems. Also, some builtin suffix in CMake should be used to enhance this, like `${CMAKE_STATIC_LIBRARY_PREFIX} and ${CMAKE_STATIC_LIBRARY_SUFFIX}`.

**Comment by gangliao** [comment]
That's very important feature for `mkl-dnn` to support Mac OS X, as you know, all of deep learning systems support GPU nowadays, but GPU kernel code only can be compiled by `Apple-clang` under Mac OS X. `Apple-clang` doesn't include `openmp`, which means that if one of deep learning system supports GPU on Mac OS X, `mkl-dnn` cannot build successfully since it depends `openmp`.

**Comment by rsdubtso** [comment]
I've updated the gist with unofficial OS X support: https://gist.github.com/rsdubtso/18d25961b15667c4a0bf523933f7acb4

I ran few tests...

I'm pretty sure that Xbyak fails to generate any code...

**Comment by rsdubtso** [comment]
I'm closing this particular discussion to avoid duplication. Please use #84 since it has a better subject.
