### ISSUE TITLE
Could you provide libmklml.a for users, not *.so?

### ISSUE THREAD

**Issue by gangliao** [01org/mkl-dnn#97]

**Comment by rsdubtso** [comment]
If you need static libraries you could probably grab just the full MKL?

**Comment by vpirogov** [comment]
Just in case Intel MKL is available free of charge [here](https://registrationcenter.intel.com/en/forms/?productid=2558&licensetype=2). You can also get it from [yum](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-yum-repo) or [apt](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo) repositories.

Is there particular reason why you need static library?

**Comment by m4ce** [comment]
any chance one can have a static library? I am in the process of building a static library for tensorflow and would like to statically link the MKL libraries.

**Comment by vpirogov** [comment]
@m4ce, you can always build static library from full Intel MKL distribution. It is available free of charge and with permissive license as indicated above.

**Comment by m4ce** [comment]
@vpirogov, thanks for your reply. Is tensorflow compatible with the Intel MKL distribution? I see it relies on this project to enable MKL support?

**Comment by tbcosta** [comment]
TensorFlow is compatible with the full Intel MKL distribution, https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture. When you run configure TensorFlow you can choose not to download MKL, and instead provide your own MKL distribution by setting the environment variable MKL_ROOT.

**Comment by vpirogov** [comment]
@nietras, Upcoming Intel MKL-DNN v1.0 will include optimized matrix-matrix multiplication for all modern platforms. With that we are retiring support for linking with Intel MKL or Intel MKL small libraries (mklml).

For now you can link Intel MKL-DNN with Intel MKL statically on Windows as well. You can get full Intel MKL distribution via a number of package managers:
* [yum](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-yum-repo)
* [apt](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo)
* [nuget](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-nuget-repo)

**Comment by nietras** [comment]
@vpirogov thanks so much for the answers, I didn't now Intel finally released the libs on nuget, that is awesome. 👍 Looking forward to MKL-DNN v1.0 then 😄 Can the OpenCL SDK also be downloaded (it does not appear to be on nuget)?

As a side note, I am working on defining .NET P/Invoke to get raw access to mkl-dnn in C#, just to be sure, is that something you are working on or interested in?

**Comment by vpirogov** [comment]
OpenCL SDK seems to be available only from [the download page at software.intel.com](https://software.intel.com/en-us/opencl-sdk). 

OpenCL Runtime for Intel Graphics Technology is available as part of the driver on Windows and available on Github for Linux. See [here](https://software.intel.com/en-us/opencl-sdk).

**Comment by vpirogov** [comment]
@nietras, C# bindings are definitely interesting. Please keep us update on your progress.
