### ISSUE TITLE
Test Failures 

### ISSUE THREAD

**Issue by Darwinian2** [01org/mkl-dnn#98]
Running tests...
Test project /home/edward2/Projects/Working.Copy/mkl-dnn/build
      Start  1: simple-net-c
 1/28 Test  #1: simple-net-c ...............................   Passed    0.28 sec
      Start  2: simple-net-cpp
 2/28 Test  #2: simple-net-cpp .............................   Passed    0.07 sec
      Start  3: simple-training-net-c
 3/28 Test  #3: simple-training-net-c ......................***Exception: Illegal  0.89 sec
      Start  4: simple-training-net-cpp
 4/28 Test  #4: simple-training-net-cpp ....................***Exception: Illegal  1.15 sec
      Start  5: api-c
 5/28 Test  #5: api-c ......................................   Passed    0.05 sec
      Start  6: test_c_symbols-c
 6/28 Test  #6: test_c_symbols-c ...........................   Passed    0.01 sec
      Start  7: test_sum
 7/28 Test  #7: test_sum ...................................   Passed    0.11 sec
      Start  8: test_reorder
 8/28 Test  #8: test_reorder ...............................   Passed    4.01 sec
      Start  9: test_concat
 9/28 Test  #9: test_concat ................................   Passed    0.10 sec
      Start 10: test_softmax_forward
10/28 Test #10: test_softmax_forward .......................   Passed    1.94 sec
      Start 11: test_eltwise
11/28 Test #11: test_eltwise ...............................   Passed   11.48 sec
      Start 12: test_relu
12/28 Test #12: test_relu ..................................   Passed    3.75 sec
      Start 13: test_lrn_forward
13/28 Test #13: test_lrn_forward ...........................   Passed    6.05 sec
      Start 14: test_lrn_backward
14/28 Test #14: test_lrn_backward ..........................   Passed   14.67 sec
      Start 15: test_pooling_forward
15/28 Test #15: test_pooling_forward .......................   Passed    7.19 sec
      Start 16: test_pooling_backward
16/28 Test #16: test_pooling_backward ......................***Exception: Illegal  0.26 sec
      Start 17: test_batch_normalization
17/28 Test #17: test_batch_normalization ...................   Passed   43.39 sec
      Start 18: test_inner_product_forward
18/28 Test #18: test_inner_product_forward .................   Passed    0.10 sec
      Start 19: test_inner_product_backward_data
19/28 Test #19: test_inner_product_backward_data ...........   Passed    0.07 sec
      Start 20: test_inner_product_backward_weights
20/28 Test #20: test_inner_product_backward_weights ........   Passed    0.53 sec
      Start 21: test_convolution_format_any
21/28 Test #21: test_convolution_format_any ................   Passed    0.03 sec
      Start 22: test_convolution_forward_f32
22/28 Test #22: test_convolution_forward_f32 ...............   Passed   73.70 sec
      Start 23: test_convolution_forward_s16s16s32
23/28 Test #23: test_convolution_forward_s16s16s32 .........   Passed   86.05 sec
      Start 24: test_convolution_relu_forward_f32
24/28 Test #24: test_convolution_relu_forward_f32 ..........   Passed    7.79 sec
      Start 25: test_convolution_relu_forward_s16s16s32
25/28 Test #25: test_convolution_relu_forward_s16s16s32 ....   Passed    3.69 sec
      Start 26: test_convolution_backward_data_f32
26/28 Test #26: test_convolution_backward_data_f32 .........   Passed    3.05 sec
      Start 27: test_convolution_backward_data_s16s16s32
27/28 Test #27: test_convolution_backward_data_s16s16s32 ...   Passed    3.11 sec
      Start 28: test_convolution_backward_weights
28/28 Test #28: test_convolution_backward_weights ..........   Passed    3.80 sec

89% tests passed, 3 tests failed out of 28

Total Test time (real) = 277.30 sec

The following tests FAILED:
          3 - simple-training-net-c (ILLEGAL)
          4 - simple-training-net-cpp (ILLEGAL)
         16 - test_pooling_backward (ILLEGAL)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
Stepping:              2
CPU MHz:               1596.000
CPU max MHz:           2927.0000
CPU min MHz:           1596.0000
BogoMIPS:              5860.96
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm ida arat epb dtherm tpr_shadow vnmi flexpriority ept vpid

Can anyone assist, I trying to compile on openSUSE Leap 42.2.

**Comment by rsdubtso** [comment]
Thanks for catching... This is a bug in JIT kernel for pooling. Can you please try this [patch](https://gist.github.com/rsdubtso/4c2bb282ddd9c0018ce4c9909a561181)?

**Comment by vpirogov** [comment]
Resolved in 3669d49f69dd3a59961e9e3059024251fcab9aef

**Comment by vpirogov** [comment]
One more defect in u8 variant of pooling for Intel SSE 4.2 is addressed in d19482317ceb878bc014f927c6d34ba2ee01b679.
