### ISSUE TITLE
What is the criteria for dividing input channels?

### ISSUE THREAD

**Issue by HAIDJ** [01org/mkl-dnn#99]
Dear MKLDNN contributor,

I am having an inquiry while looking at the mkldnn 1x1 convolution code on avx512(KNL).

In the linked code below, what is the criteria for dividing input channels(I intend to reduce_divider values)? Is it a criterion to increase reuse of input block considering L2 size of KNL?
[https://github.com/01org/mkl-dnn/blob/master/src/cpu/jit_avx512_common_1x1_conv_kernel.cpp#L747](url)

I am always thankful for your help.
Thank you,

Daejin.

**Comment by rsdubtso** [comment]
Yes, this is blocking for cache.

**Comment by HAIDJ** [comment]
As L2 cache or kernel/output size change, I would like to find the optimal reduce_divider values.

**Comment by vpirogov** [comment]
I don't think there's a simple answer to this question or you would have seen the formula in the code. As it does not look like anyone from the team was able to provide useful information I'll close this item.
